### PR TITLE
Added basic SLES compatibility.

### PR DESCRIPTION
**Pull request by darinlively**
Tested against SLES 11 SP3

### CODE REVIEW

**Comment by awood** [comment]
Bot, ok to test

**Comment by darinlively** [comment]
Is there a way for me to see the output of the failed jobs?  The hosts under the "Details" links don't resolve for me

**Comment by barnabycourt** [comment]
Bot, ok to test

**Comment by barnabycourt** [comment]
@darinlively The errors were as follows:
stylish:
```
subscription-manager.spec: E: specfile-error error: parse error in expression
subscription-manager.spec: E: specfile-error error: subscription-manager.spec:26: parseExpressionBoolean returns -1
subscription-manager.spec: E: specfile-error error: query of specfile subscription-manager.spec failed, can't parse
```

tito:
```
~/workspace/subscription-manager-tito-pull-request-builder ~/workspace/subscription-manager-tito-pull-request-builder
+ mkdir tito/
+ set -o pipefail
+ tito build --output=tito/ --test --rpm
+ tee tito_results.txt
ERROR: Unable to determine project name from spec file: /home/jenkins/workspace/subscription-manager-tito-pull-request-builder/subscription-manager.spec
```

Looks like the regex isn't parsing on the build server. Please update the pr, rebase & resubmit. If you need any info about the jenkins test environment I can provide it.

**Comment by darinlively** [comment]
Thanks for copying the error log here for me.  I pushed a new commit to the PR with the updates.

**Comment by wottop** [comment]
buildbot: retest this please

**Comment by awood** [comment]
@darinlively Looks good (test failures are due to an unrelated issue) but my only concern is that the code will bitrot.  None of us use SLES for daily development.  I'm supposing that we'll need to set up an SLES Jenkins node, but if you can point us to a doc that outlines the basic differences or gotchas, I'll read it and try and keep out any obvious incompatibilities.

**Comment by darinlively** [comment]
Hey @awood -- Thanks.

I understand the concern about bitrot.  I can say that if all goes well, I will be invested in making sure these tools continue to work for SLES for the foreseeable future.  Fortunately almost all of the changes I had to make were in the build/packing code and not the functional code.  

Unfortunately I don't have a specific doc on the differences between RHEL and SLES, but I can share my findings.  

1. The most common differences were simply the names of packages in the build dependencies (python-devel vs. python2-devel or m2crypto vs. python-m2crypto, etc).  
2. Library paths:  On SLES libexecdir resolves to /usr/lib64.  On RHEL it's /usr/libexec.  As long as the path is evaluated instead of hardcoded, it should be good.
3.  Init scripts:  SLES requires some difference syntax for LSB headers, and SLES has some different global functions (/etc/rc.status instead of /etc/init.d/functions), as well as init scripts living in /etc/init.d instead of /etc/rc.d/init.d.

I probably should have included this in the original PR, but these are all of the PRs I submitted to get the katello-agent and dependencies working on SLES:
https://github.com/candlepin/subscription-manager/pull/1419
https://github.com/candlepin/python-rhsm/pull/168
https://github.com/Katello/katello-packaging/pull/220
https://github.com/jortel/gofer/pull/60
https://github.com/pulp/pulp/pull/2566
https://github.com/pulp/pulp_rpm/pull/871

**Pull request merged**
