### PR TITLE
1268060: Add 'cancel' back to s-m-gui register.

### PR DESCRIPTION
**Pull request by alikins**
Add a 'Cancel' button back to s-m-gui register dialog.

### CODE REVIEW

**Comment by cnsnyder** [comment]
I'm not sure we should merge this without being able to cancel async processes (such as registration, auto-attach, etc).

**Comment by barnabycourt** [comment]
This should detect whether we are in initial setup and not display the cancel in that case.

**Comment by barnabycourt** [comment]
Instead of Cancel, use Close as we are not reversing changes.

**Comment by cnsnyder** [comment]
The cancel button has been renamed/relabelled Close in the same way found in factsdialog.
This has been tested on initial-setup, the close button does not appear.
This has also been tested using other languages, the translations appear to be working.

The benefit of leaving the close button enabled is that a user is free to close the window at any point, even during a long running transaction. The consequence of this benefit is that async processes started by the now closed window can still complete unexpectedly.

**Pull request merged**
