### PR TITLE
Add --no-content switch to cat-manifest to reduce output.

### PR DESCRIPTION
**Pull request by awood**

### CODE REVIEW

**Comment by wottop** [comment]
buildbot: retest this please

**Comment by wottop** [comment]
nosetest exception

======================================================================
ERROR: test_cat_manifest (test.test_rct_manifest_command.RCTManifestCommandTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wpoteat/subscription-manager/test/test_rct_manifest_command.py", line 71, in test_cat_manifest
    catman._do_command()
  File "/home/wpoteat/subscription-manager/src/rct/manifest_commands.py", line 284, in _do_command
    self._print_products(temp)
  File "/home/wpoteat/subscription-manager/src/rct/manifest_commands.py", line 268, in _print_products
    if not self.options.no_content:
AttributeError: 'CatManifestCommand' object has no attribute 'options'
-------------------- >> begin captured stdout << ---------------------

**Comment by jsefler** [comment]
I think this pull request title should reference the requesting bugzilla
Bug 1336883 - [RFE] Update the 'rct' command to allow not outputting content-set data

**Comment by wottop** [comment]
ack

**Pull request merged**
