### PR TITLE
Releaser for Centos

### PR DESCRIPTION
**Pull request by wottop**

### CODE REVIEW

**Comment by wottop** [comment]
Note that this is used in conjunction with the tito fork:

https://github.com/wottop/tito/tree/add-centpkg

**Comment by ptoscano** [comment]
> Note that this is used in conjunction with the tito fork:
> 
> https://github.com/wottop/tito

Specifically, https://github.com/rpm-software-management/tito/pull/403

**Comment by wottop** [comment]
The final version of the tito bit is in the master branch of my fork: https://github.com/wottop/tito

**Comment by ptoscano** [comment]
> The final version of the tito bit is in the master branch of my fork: https://github.com/wottop/tito

Now available as https://github.com/rpm-software-management/tito/pull/405

**Review by cnsnyder — APPROVED** [review]
This worked well for me for a release to centos 9 stream.

**Review by jirihnidek — APPROVED** [review]
ACK

**Pull request merged**
