### PR TITLE
1335537: Fix typo in proxy message

### PR DESCRIPTION
**Pull request by wottop**

### CODE REVIEW

**Comment by cnsnyder** [comment]
@candlepin/jenkins-bot Please retest this

**Comment by barnabycourt** [comment]
@candlepin-pull-request-bot test this please

**Comment by cnsnyder** [comment]
@candlepin-pull-request-bot Please retest this

**Comment by cnsnyder** [comment]
I do not believe the test failures have anything to do with the change to this string. Merging.

**Pull request merged**
