### PR TITLE
Move to fileConfig based logging.

### PR DESCRIPTION
**Pull request by alikins**
The default logging config is defined in
/etc/rhsm/logging.conf now. So general logging
config like log level and log file name can be
set here.

In addition, configuration of syslog based logging can
be done here as well. For example, you could point
the logger for 'rhsm-app' to use the syslog handler.
The 'handler_syslog' section could point syslog local
or remote.

Log formats are also defined there.

### CODE REVIEW

**Comment by alikins** [comment]
This is kind of the next jump past https://github.com/candlepin/subscription-manager/pull/1124

The next step would be to support the json or yaml loggers in python 2.7.

I also have no idea yet if this will work on RHEL6, so thats likely broken.

**Comment by alikins** [comment]
supporting multiple log config files is a little weird... there are two ways to do it

1) Combine the config files into one config object using ConfigParsers support for specifying multiple filenames

   Kind of works, but it's not an entirely expected behaviour.

2) calling fileConfig() on multiple config files

   One odd issue here is that each config file needs to be complete by itself. They need to specify at least a minimal logger/handlers/formatters, and each needs to redefine the root logger.

Not entirely sure what the expected behaviour would be.

**Comment by alikins** [comment]
file_config takes a logging_config arg now

**Comment by awood** [comment]
ACK

**Comment by alikins** [comment]
should be rebased to master now, and with some commit squashing.

**Comment by alikins** [comment]
Ah! I did change the default log format. It included the extra '%(name)s' in there. Removing now...

**Pull request merged**
