### PR TITLE
1176219: Connection errors will now print a message to stderr.

### PR DESCRIPTION
**Pull request by Ceiu**
- The StatusCache object will now print a warning to stderr if it
  is unable to connect to the server, but will continue with cached
  status instead.

### CODE REVIEW

**Comment by alikins** [comment]
NACK atm, Someone using the gui won't see the stderr output. 

Maybe a warn callback, with cli providing a stderr handler and gui showing a warning dialog?

Unit tests wouldn't need to capture stderr out then.

**Comment by alikins** [comment]
(Though, for gui, a warning dialog could get annoying. Some sort of 'offline' indicator would be better, but likely not worth the effort.)

**Comment by Ceiu** [comment]
Alright, take a peek at that.

I'm not entirely fond of exposing implementation details globally like that, but it's cleaner than having to juggle and pass instances of the StatusCache and/or callbacks around.

**Comment by alikins** [comment]
Hmm, thats a bit complicated now. If we can defer that bug post this release, lets revisit next sprint

**Comment by Ceiu** [comment]
That works with me.

**Pull request closed without merging**
