### PR TITLE
Moved rhsm out of ./src to be able to create pypi package

### PR DESCRIPTION
**Pull request by jirihnidek**
* It was necessary to move some files to be able to create
  Python package using setup.py
  - The rhsm Python modules was moved from ./src/rhsm to ./rhsm/src/rhsm
  - The src/certificate.c was moved to ./rhsm/src/
  - There is new setup.py in rhsm
* It was necessary to change subscription-manager.spec
  - Many Python modules are installed to /usr/lib/ and not /usr/lib64
    now, because ./setup.py used for building and installing
    subscription-manager does not building binary Python module
    _certificate*.so
  - Only rhsm package is installed into /usr/lib64
* Added instruction about uploading of rhsm module to pypi.org into
  rhsm/README.md
* Changed some lint modules to be able to run python ./setup.py lint
  locally
* Changed the latest version of rhsm to 1.19.4
* Tested upload of rhsm to test.pypi.org:

  https://test.pypi.org/manage/project/rhsm/releases/

### CODE REVIEW

**Comment by jirihnidek** [comment]
@candlepin-bot retest this please

**Comment by wottop** [comment]
I don't think this is in our code. Who do we get to look at it? Also fix the conflict.

python ./setup.py sdist && \
        mv dist/$fn.tar.gz /home/user/cockpit-project/bots/make-checkout-workdir/dist/subscription-manager.tar.gz
  File "./setup.py", line 413
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax
  File "./setup.py", line 413
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax

**Comment by jirihnidek** [comment]
> I don't think this is in our code. Who do we get to look at it? Also fix the conflict.
> 
> python ./setup.py sdist &&
> mv dist/$fn.tar.gz /home/user/cockpit-project/bots/make-checkout-workdir/dist/subscription-manager.tar.gz
> File "./setup.py", line 413
> <<<<<<< HEAD
> ^
> SyntaxError: invalid syntax
> File "./setup.py", line 413
> <<<<<<< HEAD
> ^
> SyntaxError: invalid syntax

Oh, in what file do you see this conflict?

**Comment by wottop** [comment]
Conflicting files
src/rhsm/connection.py

**Comment by wottop** [comment]
I rebased to current master. The conflict is gone, but the tests are still in limbo.

**Pull request closed without merging**
