### PR TITLE
1443570: Update retired article reference

### PR DESCRIPTION
**Pull request by redhatrises**
- bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1443570

### CODE REVIEW

**Comment by kahowell** [comment]
okay to test

**Comment by jirihnidek** [comment]
Ack, I will only amend commit log to follow our rule.

**Comment by kahowell** [comment]
ok to test

**Comment by jirihnidek** [comment]
retest this please

**Comment by jirihnidek** [comment]
@redhatrises please, modify your commit log to follow our rule for commit logs. The first line of commit log should begin with number of bugzilla bug report. In this case: `1443570: Update retired article reference` You can achieve this by executing following commands:

```bash
git commit --amend
# modify commit log in your "favorite" editor to follow our rule
git push --force origin redhatrises/1443570
```

I tried to do it myself, but I don' have push rights to your remote repository.

Thanks in advance.

**Comment by redhatrises** [comment]
Apologies @jirihnidek. Thanks for letting me know about the PR rules. I have fixed the commit message.

**Comment by jirihnidek** [comment]
@redhatrises Thanks for your PR and fast response.

**Pull request merged**
