### PR TITLE
1278472: Change default registration url to subscription.rhsm.redhat.com

### PR DESCRIPTION
**Pull request by wottop**

### CODE REVIEW

**Comment by alikins** [comment]
Man pages need update as well.

The docs should also mention that the new name should not be used with old clients, as subscription.RHSM.redhat.com may use TLS options really old clients may not be able to support.

**Comment by wottop** [comment]
testbot: retest this please

**Comment by alikins** [comment]
NACK, migrate/migrate.py:is_hosted() needs to work for subscription.rhn.redhat.com or subscription.rhsm.redhat.com and (stage/dev...). The test case should work for either.

**Comment by cnsnyder** [comment]
Migrate/migrate.py:is_hosted() seems to be fixed although I can't see the referenced BZ. @alikins anything else necessary for an ACK?

**Comment by alikins** [comment]
ACK

**Pull request merged**
