### PR TITLE
1283749: Upgrade the dialogs to error when required fields are blank.

### PR DESCRIPTION
**Pull request by wottop**
Also corrected a couple of stylish issues.

### CODE REVIEW

**Comment by alikins** [comment]
I'm not sure I agree that 1283749 is a bug. 

Error tends to mean fatal errors, register-error signals are also handled
slightly differently that register-message signals (initial-setup for example,
expects a different second args...)

Does initial-setup break?

**Comment by wottop** [comment]
It appears that it is hard to automate the test. The warning implies that the registration will continue and it will not.

**Comment by wottop** [comment]
buildbot: retest this please

**Comment by cnsnyder** [comment]
Looks good to me. Works on rhel-6.8. The dialogs don't look any different on rhel-7. This doesn't seem to be an issue with the implementation of this fix. ACK.

**Pull request merged**
