### PR TITLE
[1.28] jenkins: switch stylish job to Python 3

### PR DESCRIPTION
**Pull request by jirihnidek**
Cherry picked commit from #2621

subscription-manager does not support Python 2 anymore, so switch the
stylish script to the Python 3 version.

Also, stop using the 'subman-centos7' agent for it, as it clearly does
not support Python 3; the default 'subman' agent will work fine.

### CODE REVIEW

**Comment by ptoscano** [comment]
You will need to backport also some commits (if not all) from #2623 too; in particular, at least 626f8b2ada8a3175b287aee1b721998687ef86d6 and 902ddc3e3c88ca21d7ba63ad1b60bf4c699c1747.

**Comment by jirihnidek** [comment]
Stylish tests found stylish errors, but it is expected behavior for "new" code.

**Comment by ptoscano** [comment]
Either you backport also 404b30086946098adb4337eabc32e41efe77f432, 62d907c1603905a7b8732eb738c7719111dbde2c, fea1618913b7021452cdf600f06554fe36aeefc6 and 42351c3e630e937ca03ef187ba88eead7fe17e65, or tweak the `.flake8` file a bit more.

**Comment by ptoscano** [comment]
Another alternative is to simply backport #2623 and then #2621, both fully. This way there are also slightly less differences between `main` and `subscription-manager-1.28`.

**Comment by ptoscano** [comment]
Oh, that's good now, thanks. The extra changed is indeed needed as it seems those bits were reformatted in the managercli split.

**Pull request merged**
