### PR TITLE
1985845: Fix sub-man service-level --show

### PR DESCRIPTION
**Pull request by jirihnidek**
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1985845
* When candlepin has syspurpose capability, then use benefits
  of SyncedStore

### CODE REVIEW

**Comment by jirihnidek** [comment]
How to test this issue:

1. Register and unset service-level
2. Get current consumer UUID using `subscription-manager identity`
3. Use consumer UUID for altering system purpose attributes on candlepin server using curl like this (don't forget to replace values in <value> with your real value):
```
curl --verbose -k -u admin:admin --request PUT --data \
    '{"role": "", "addOns": [], "usage": "", "serviceLevel": "Premium"}' \
    --header 'content-type: application/json' \
    https://<your_candlepin_server>:8443/candlepin/consumers/<your_consumer_UUID>
```
4. Try to get service-level using: `subscription-manager syspurpose service-level --show`
5. Check that value 'Premium' is also set in `/etc/rhsm/syspurpose/syspurpose.json'

**Comment by ptoscano** [comment]
A couple of possibly stupid questions:
- from what I get from the instructions here and in the bz, it seems the problem happens when the service level is changed on the entitlement server for a register consumer, and that consumer does not get the server-side update; is that correct?
- I guess this affects only service-level because its slightly different syspurpose implementation than addons/role/usage?

**Comment by jirihnidek** [comment]
> A couple of possibly stupid questions:
> 
>     * from what I get from the instructions here and in the bz, it seems the problem happens when the service level is changed on the entitlement server for a register consumer, and that consumer does not get the server-side update; is that correct?

Yeah, it is correct. The issue described in BZ is related to the case, when service-level is changed using web UI on Satellite server.

> 
>     * I guess this affects only service-level because its slightly different syspurpose implementation than addons/role/usage?

It is also correct. Other syspurpose attributes (addons/role/usage) are not affected by this issue.

**Review by ptoscano — APPROVED** [review]
Thanks for the answers & the instructions, much helpful!

LGTM, and works fine for me too.

**Pull request merged**
