### PR TITLE
Ignore missing repo if manage_repo is false

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by jirihnidek** [comment]
@candlepin-bot ok to test

**Comment by wottop** [comment]
buildbot: retest this please

**Comment by sbernhard** [comment]
As you know, I'm not able to access the test results. What do you think about the change?

**Comment by wottop** [comment]
buildbot: retest this please

**Comment by wottop** [comment]
The change is acceptable. I will make sure the tests are able to complete before it is merged.

**Comment by wottop** [comment]
buildbot: retest this please

**Comment by wottop** [comment]
ack

**Pull request merged**
