### PR TITLE
1500213: Sumnan-gui: force reset no_proxy env. variable

### PR DESCRIPTION
**Pull request by jirihnidek**
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1500213
* It is necessary to reset env. var. no_proxy due to
  check in rhsm/connection.py:290

### CODE REVIEW

**Comment by jirihnidek** [comment]
[1500213 - GUI : Proxy is not taken into consideration when you uncheck the "BYPASS the HTTP Proxy for specific hosts/domains" checkbox and enter some invalid proxy](https://trello.com/c/X4A3axWS/731-1500213-gui-proxy-is-not-taken-into-consideration-when-you-uncheck-the-bypass-the-http-proxy-for-specific-hosts-domains-checkbox)

**Comment by kahowell** [comment]
> This will make it such that the GUI effectively ignores proxy-related environment variables.

An alternative would be to display the environment variables in the GUI somehow, and convey that the user may need to unset the environment variables if they want to override them. I think this alternative is not worth exploring though...

**Comment by jirihnidek** [comment]
@kahowell good point. I updated the PR and I filled BZ bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1538564

**Comment by jirihnidek** [comment]
BTW: I vote for displaying of environment variables in the GUI and add/change warning message in register dialog.

**Comment by wottop** [comment]
retest this please

**Comment by wottop** [comment]
retest this please

**Comment by wottop** [comment]
retest this please

**Comment by wottop** [comment]
Please correct the commit message to 'Subman'

**Comment by kahowell** [comment]
@jirihnidek what I'm thinking now is this: if we address [bz1538564](https://bugzilla.redhat.com/show_bug.cgi?id=1538564), then we won't need this fix. I'm thinking we just close as WONTFIX [bz1500213](https://bugzilla.redhat.com/show_bug.cgi?id=1500213), and close this PR (Otherwise, we'd change the behavior in this PR, and then undo this PR with work on the second BZ...)... thoughts?

**Comment by jirihnidek** [comment]
@kahowell I have no problem with your proposal 👍

**Comment by kahowell** [comment]
Closing in favor of future work to address [bz1538564](https://bugzilla.redhat.com/show_bug.cgi?id=1538564).

**Pull request closed without merging**
