### PR TITLE
1804114: New D-Bus method SetAll; ENT-2124

### PR DESCRIPTION
**Pull request by jirihnidek**
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1804114
* Implemented method SetAll()
  - It is possible to set all configuration option or
    several configuration options
  - This method is prefered, because it minimize number of
    writing to configuration file rhsm.conf
* Implemented temporary disablement of directory watcher of
  file system monitor.
  - When rhsm.service write something to rhsm.conf and temporary
    disablement would not be implemented, then configuration
    options would be read back from rhsm.conf, because i-notify
    detected some changes in rhsm.conf. When mulitple values
    are set using D-Bus method Set() or SetAll(), then there
    is danger that some WIP values would be read back to
    rhsm.service and it would not be possible to e.g. register
    system to candlepin server.
* Moved logutil from subscription_manager to rhsm
* Refactored usage of i-notify a little bit. Added many comments
  and renamed some methods to be more descriptive
* Fixed few unit tests

### CODE REVIEW

**Comment by cnsnyder** [comment]
@jirihnidek We should figure out what is failing on the Cockpit tests though.

**Comment by jirihnidek** [comment]
> @jirihnidek We should figure out what is failing on the Cockpit tests though.

It's fair. All checks have failed. I will contact cockpit team.

**Comment by mvollmer** [comment]
The journal of the failed tests contains this:
```
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]: ERROR [root:54] DBus service startup failed
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]: Traceback (most recent call last):
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]:   File "/usr/lib64/python3.6/site-packages/subscription_manager-1.27.0-py3.6-linux-x86_64.egg/subscription_manager/scripts/rhsm_service.py", line 52, in main
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]:     sys.exit(service_wrapper.main(sys.argv, object_classes=object_classes))
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]:   File "/usr/lib64/python3.6/site-packages/subscription_manager-1.27.0-py3.6-linux-x86_64.egg/rhsmlib/dbus/service_wrapper.py", line 70, in main
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]:     object_classes=object_classes).run()
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]:   File "/usr/lib64/python3.6/site-packages/subscription_manager-1.27.0-py3.6-linux-x86_64.egg/rhsmlib/dbus/server.py", line 61, in __new__
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]:     cls.INSTANCE = object.__new__(cls, *args, **kwargs)
Mar 03 07:24:03 localhost.localdomain rhsm-service[1588]: TypeError: object() takes no parameters
Mar 03 07:24:03 localhost.localdomain systemd[1]: Started RHSM dbus service.
Mar 03 07:24:24 localhost.localdomain dbus-daemon[826]: [system] Failed to activate service 'com.redhat.RHSM1': timed out (service_start_timeout=25000ms)
```

**Comment by M4rtinK** [comment]
Unfortunately I am seeing the same traceback when trying to use the subscription manager package scratch build with this PR with Anaconda:

```
Mar 04 11:33:08 localhost rhsm-service[3825]: ERROR [root:54] DBus service startup failed
Mar 04 11:33:08 localhost rhsm-service[3825]: Traceback (most recent call last):
Mar 04 11:33:08 localhost rhsm-service[3825]:   File "/usr/lib64/python3.6/site-packages/subscription_manager/scripts/rhsm_service.py", line 52, in main
Mar 04 11:33:08 localhost rhsm-service[3825]:     sys.exit(service_wrapper.main(sys.argv, object_classes=object_classes))
Mar 04 11:33:08 localhost rhsm-service[3825]:   File "/usr/lib64/python3.6/site-packages/rhsmlib/dbus/service_wrapper.py", line 70, in main
Mar 04 11:33:08 localhost rhsm-service[3825]:     object_classes=object_classes).run()
Mar 04 11:33:08 localhost rhsm-service[3825]:   File "/usr/lib64/python3.6/site-packages/rhsmlib/dbus/server.py", line 61, in __new__
Mar 04 11:33:08 localhost rhsm-service[3825]:     cls.INSTANCE = object.__new__(cls, *args, **kwargs)
Mar 04 11:33:08 localhost rhsm-service[3825]: TypeError: object() takes no parameters
```

**Comment by M4rtinK** [comment]
Still getting a crash with the latest version when running in the RHEL8 installation environment:
```
Mar 05 16:19:05 localhost rhsm-service[3239]: Traceback (most recent call last):
Mar 05 16:19:05 localhost rhsm-service[3239]:   File "/usr/libexec/rhsm-service", line 11, in <module>
Mar 05 16:19:05 localhost rhsm-service[3239]:     load_entry_point('subscription-manager==1.26.13', 'console_scripts', 'rhsm-service')()
Mar 05 16:19:05 localhost rhsm-service[3239]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
Mar 05 16:19:05 localhost rhsm-service[3239]:     return get_distribution(dist).load_entry_point(group, name)
Mar 05 16:19:05 localhost rhsm-service[3239]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
Mar 05 16:19:05 localhost rhsm-service[3239]:     return ep.load()
Mar 05 16:19:05 localhost rhsm-service[3239]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
Mar 05 16:19:05 localhost rhsm-service[3239]:     return self.resolve()
Mar 05 16:19:05 localhost rhsm-service[3239]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
Mar 05 16:19:05 localhost rhsm-service[3239]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Mar 05 16:19:05 localhost rhsm-service[3239]:   File "/usr/lib64/python3.6/site-packages/subscription_manager/scripts/rhsm_service.py", line 35, in <module>
Mar 05 16:19:05 localhost rhsm-service[3239]:     from rhsmlib.dbus import service_wrapper
Mar 05 16:19:05 localhost rhsm-service[3239]:   File "/usr/lib64/python3.6/site-packages/rhsmlib/dbus/service_wrapper.py", line 22, in <module>
Mar 05 16:19:05 localhost rhsm-service[3239]:     from rhsmlib.dbus import server
Mar 05 16:19:05 localhost rhsm-service[3239]:   File "/usr/lib64/python3.6/site-packages/rhsmlib/dbus/server.py", line 42, in <module>
Mar 05 16:19:05 localhost rhsm-service[3239]:     init_logger(parser)
Mar 05 16:19:05 localhost rhsm-service[3239]: TypeError: init_logger() takes 0 positional arguments but 1 was given
Mar 05 16:19:05 localhost systemd[1]: rhsm.service: Main process exited, code=exited, status=1/FAILURE
Mar 05 16:19:05 localhost systemd[1]: rhsm.service: Failed with result 'exit-code'.
Mar 05 16:19:05 localhost systemd[1]: Failed to start RHSM dbus service.
```

**Comment by jirihnidek** [comment]
@candlepin-bot please retest

**Pull request merged**
