### PR TITLE
1371632: Disallow connection test w/ blank proxy

### PR DESCRIPTION
**Pull request by kahowell**

### CODE REVIEW

**Comment by barnabycourt** [comment]
@kahowell please update the bugzilla with a github external tracker that points back to this PR

**Comment by kahowell** [comment]
@barnabycourt done

**Comment by cnsnyder** [comment]
@kahowell Should we allow them to test connection when they have checked the "Use Authentication..." box but have not entered in any credentials?

**Comment by kahowell** [comment]
@cnsnyder, it's less severe, but might as well go ahead and incorporate that too. I'll update this branch/PR shortly.

**Comment by cnsnyder** [comment]
Works well for me! Looks great. It does seem to be a cleaner fix. :+1:

**Pull request merged**
