### PR TITLE
1447722: use socket.getaddrinfo() to mimic hostname -f cmd

### PR DESCRIPTION
**Pull request by jirihnidek**
* Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1447722
* SELinux was preventing calling hostname at RHEL 7.4 and this
  is more Pythonic solution.

### CODE REVIEW

**Comment by jirihnidek** [comment]
[BUG 1447722: Error reading networking information: [Errno 13] Permission denied](https://trello.com/c/0cgf4vdQ/374-bug-1447722-error-reading-networking-information-errno-13-permission-denied)

**Comment by kahowell** [comment]
[As I noted in the bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1447722#c5), we need to make sure that we don't regress on [bug 1401394](https://bugzilla.redhat.com/show_bug.cgi?id=1401394)... I found that you can get an environment set up by doing the following:

1. Edit `/etc/hosts`: at the top of the file create new aliases for the localhost interfaces (ex:)
```
127.0.0.1 khowell-ipv4.example.com khowell
::1 khowell-ipv6.example.com khowell
```

2. Set hostname to just the hostname (*not* fqdn, no periods allowed)
```
$ sudo hostname khowell
```

3. Observe `hostname --fqdn`
```
$ hostname --fqdn
khowell-ipv4.example.com
```

4. Observe what is reported by subscription-manager for fqdn fact:
```
$ sudo subscription-manager facts | grep fqdn
network.fqdn: khowell-ipv6.example.com
```

Looking at how FQDN is implemented in both python and hostname (you can get the source for hostname via srpm or pretty close with http://http.debian.net/debian/pool/main/h/hostname/hostname_3.15.tar.gz), I think we can actually get the same effect in python by doing something like the following:
```python
import socket
fqdn_ipv4 = socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET, socket.SOCK_DGRAM, 0, socket.AI_CANONNAME)[0][3]
fqdn_ipv6 = socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET6, socket.SOCK_DGRAM, 0, socket.AI_CANONNAME)[0][3]
```
with some appropriate bounds checking and preferring one over the other as appropriate...

See https://docs.python.org/2/library/socket.html#socket.getaddrinfo for API documentation

**Comment by awood** [comment]
The other alternative that occurred to me is to shell out to `uname -n` instead of `hostname`.  I'm wagering SELinux won't complain about calling `uname` since that's just an informational request instead of the `hostname` binary which has write capabilities.  If you run `hostname` through `strace` you'll see it's going down to the `uname` system call anyway.

**Comment by kahowell** [comment]
Looks good to me. I tested out in vagrant by using the following:
```bash
echo -e "127.0.0.1 centos7.ipv4.example.com centos7\n::1 centos7.ipv6.example.com centos7\n$(cat /etc/hosts)" | sudo tee /etc/hosts; sudo hostname centos7
sudo subscription-manager facts | grep fqdn  # see what subman thinks fqdn is
hostname -f  # see what hostname -f thinks fqdn is
```

Tried this is fedora25, centos6, centos7 with good results :smile:

**Pull request merged**
