### PR TITLE
Remove logrotating in favor of logrotate daemon. solves #1345

### PR DESCRIPTION
**Pull request by sspreitzer**

### CODE REVIEW

**Comment by dgoodwin** [comment]
Can one of the admins verify this patch?

**Comment by dgoodwin** [comment]
Can one of the admins verify this patch?

**Comment by dgoodwin** [comment]
Can one of the admins verify this patch?

**Comment by awood** [comment]
candlepin-bot, ok to test

**Comment by alikins** [comment]
In theory, if someone is using RotatingFileHandler specific args in /etc/rhsm/logging.conf, this could break previously working config. (ie, maxBytes'/backupCount)

In practice, I suspect no one does that though. RHSMLogHandler could potentially filter those out to be extra careful.

**Comment by alikins** [comment]
ACK.

**Comment by alikins** [comment]
(re RotatingFIleHandler kwargs... doesn't matter since the file config doesn't support using keyword args so not an issue)

**Comment by sspreitzer** [comment]
Okay, thanks for merging!

**Pull request merged**
