### PR TITLE
1920020: Check the Log Level to make sure it is valid, if not set it …

### PR DESCRIPTION
**Pull request by tlhmerry9**
…to INFO

### CODE REVIEW

**Comment by tlhmerry9** [comment]
To Test:

[vagrant@fedora32 vagrant]$ sudo subscription-manager config --logging.default_log_level=FOO
Invalid Log Level: FOO, setting to INFO.
Use: subscription-manager config --logging.default_log_level= to set the default_log_level.
Invalid Log Level: FOO, setting to INFO.
Use: subscription-manager config --logging.default_log_level= to set the default_log_level.
[vagrant@fedora32 vagrant]$ sudo subscription-manager version
Invalid Log Level: FOO, setting to INFO.
Use: subscription-manager config --logging.default_log_level= to set the default_log_level.
Invalid Log Level: FOO, setting to INFO.
Use: subscription-manager config --logging.default_log_level= to set the default_log_level.
server type: This system is currently not registered.
subscription management server: 3.2.11-1
subscription management rules: 5.41
subscription-manager: RPM_VERSION

**Review by jirihnidek — COMMENTED** [review]
I'm little bit confuse by GitHub. I can see that this change has been merged to master 4 days ago.  The PR is following: #2468 (there were three commits). This PR has same change and it has only one commit. Is purpose of this PR to squash commits?

**Comment by tlhmerry9** [comment]
> I'm little bit confuse by GitHub. I can see that this change has been merged to master 4 days ago. The PR is following: #2468 (there were three commits). This PR has same change and it has only one commit. Is purpose of this PR to squash commits?

Hi this is for ENT-3626 for the branch subscription-manager-1.28.  If I did something incorrectly, please let me know.

**Comment by jirihnidek** [comment]
> Hi this is for ENT-3626 for the branch subscription-manager-1.28. If I did something incorrectly, please let me know.

The PR is opened against master branch. Look at the top of the PR. I think that you have to close this PR and open it once again against `subscription-manager-1.28` branch.

**Comment by tlhmerry9** [comment]
> > Hi this is for ENT-3626 for the branch subscription-manager-1.28. If I did something incorrectly, please let me know.
> 
> The PR is opened against master branch. Look at the top of the PR. I think that you have to close this PR and open it once again against `subscription-manager-1.28` branch.

ok, I will do that this morning.  Sorry for the confusion!

**Pull request closed without merging**
