### PR TITLE
Sync the syspurpose on runs of each relevant command

### PR DESCRIPTION
**Pull request by cnsnyder**
This revises the Role, Usage, Addons, and ServiceLevel Commands.
Each of these now perform the sync action and display a message with a course of action if the result is not as expected.

The way to get this message to show up is in the reproducer steps in [This bug](https://bugzilla.redhat.com/show_bug.cgi?id=1615404)

### CODE REVIEW

**Comment by cnsnyder** [comment]
@candlepin-pull-request-bot please retest this.

**Comment by wottop** [comment]
When I run locally, I get

optparse.OptionConflictError: option --set: conflicting option string(s): --set

**Comment by cnsnyder** [comment]
@wottop  That is fixed now. Along with other updates! Will ask @jirihnidek for review in the meanwhile as he'll be on before us tomorrow.

**Comment by jirihnidek** [comment]
@cnsnyder I try to fix most of issues in this PR.

**Comment by jirihnidek** [comment]
@cnsnyder I tried to fix several issues. Some unit tests are still falling. I will try to fix it later.

**Comment by cnsnyder** [comment]
@candlepin-pull-request-bot Retest this please

**Comment by cnsnyder** [comment]
@candlepin-pull-request-bot Retest this please

**Comment by cnsnyder** [comment]
@candlepin-pull-request-bot Retest this please

**Comment by cnsnyder** [comment]
@candlepin-pull-request-bot Retest this please

**Comment by wottop** [comment]
ack

**Pull request merged**
