### PR TITLE
Adding a warning in case repos-override is used with repos disabled

### PR DESCRIPTION
**Pull request by nguyenfilip**

### CODE REVIEW

**Comment by nguyenfilip** [comment]
retest this please

**Comment by nguyenfilip** [comment]
retest this please

**Comment by alikins** [comment]
Add the bugzilla # to the beginning of the commit status line. ie:

1257943: Adding a warning to repo-override command when manage_repos = 0 

(and squash those commits together)

**Comment by nguyenfilip** [comment]
Squashed! :-)

**Comment by alikins** [comment]
ACK

**Pull request merged**
