### PR TITLE
Query.na_dict() has been renamed in dnf 2.0

### PR DESCRIPTION
**Pull request by MichaelMraka**
fixing
'Query' object has no attribute 'na_dict'

### CODE REVIEW

**Comment by barnabycourt** [comment]
ok to test

**Comment by barnabycourt** [comment]
@MichaelMraka is the _na_dict() method available in DNF prior to 2.0?

**Comment by MichaelMraka** [comment]
@barnabycourt: Unfortunately it isn't.

**Comment by barnabycourt** [comment]
@MichaelMraka Is there a means you would recommend to write this in order to support DNF 1.x and 2.x?

**Comment by MichaelMraka** [comment]
@barnabycourt: Right, this one should work on both versions.

**Comment by kahowell** [comment]
LGTM, and all issues were addressed. Merging squashed commit.

**Pull request merged**
