### PR TITLE
[Cherry pick to 8.5] Bug 1879856 - Warning message shouldnot be displayed when user tries to set valid syspurpose attributes with random case

### PR DESCRIPTION
**Pull request by tlhmerry9**
porting fix to subscription-manager-1.28

### CODE REVIEW

**Comment by jirihnidek** [comment]
@tlhmerry9 This PR has conflict. Please resolve it.

**Comment by tlhmerry9** [comment]
didn't mean to close - was rebasing

**Comment by tlhmerry9** [comment]
Github merged and closed this when I rebased to 1.28 -

**Comment by jirihnidek** [comment]
@cnsnyder Hi, I'm little bit confused. Did you force push anything to this branch or did you force push directly to `subscription-manager-1.28`?

**Comment by tlhmerry9** [comment]
Looking into this, I am also a bit confused.  Pino and I were stepping on each others toes, and when we finally got this branch looking good, we were told to stop any work on 1.28 as @cnsnyder was working on it.  I would think he would be the best person to answer the question.  I only force pushed to this branch.  

I will resolve the conflict.

**Review by jirihnidek — APPROVED** [review]
ACK

**Pull request merged**
