### PR TITLE
Alikins/gui fix and kickstart

### PR DESCRIPTION
**Pull request by alikins**
Kickstart support isn't 100% yet, but it's getting there.

Since this is going to be a large'ish branch, I wouldn't mind some eyes on it.

### CODE REVIEW

**Comment by wottop** [comment]
Running it through initial setup:
Rogue output: " replace me with poplate" on command line
The "cancel" and "next" buttons seem jammed together and shoved over to the side [out of our control?]
While registering, the 'register' button should be disabled. Repeated clicks causes errors. Similar for attach process.

**Comment by alikins** [comment]
> Rogue output: " replace me with poplate" on command line

Yup, still wip in progress.

> The "cancel" and "next" buttons seem jammed together and shoved over to the side [out of our control?]

Thats changed in https://github.com/candlepin/subscription-manager/pull/1286

> While registering, the 'register' button should be disabled. Repeated clicks causes errors. Similar for attach process.

There are existing bz's for that (for ex, https://bugzilla.redhat.com/show_bug.cgi?id=1261006)
This branch doesn't address that.

**Comment by alikins** [comment]
Looking for feedback on the design and code.

**Comment by alikins** [comment]
I'll rebase and squash this before merge.

**Comment by alikins** [comment]
> Rogue output: " replace me with poplate" on command line

fixed.

**Comment by alikins** [comment]
about to squash/rebase this

**Comment by alikins** [comment]
rebased now

**Comment by cnsnyder** [comment]
the cancel button, if used during initial-setup, seems to behave strangely. More specifically it will take me back to the previous screen only occasionally. For example on the confirm subscriptions screen, pressing cancel will take me back to the "Attaching" screen, but the cancel button if pressed there will not take me any further back.

**Comment by cnsnyder** [comment]
screenshot_rhel7 0-3_2015-09-28_11 43 09

After pressing cancel during attach, then going back to the main screen and once again returning to our subscription management section I got this interesting red bar along the bottom of the screen. Not entirely sure if that should be possible or if that is within the scope of the changes for this PR

**Comment by alikins** [comment]
re: red bar

On going back to the RHSM spoke from the main hub, if the system is registered already, it will skip to trying to autoattach (findings service levels, testing them, auto picking one if there is only one, etc).
If that autoattach then fails, it will show that error message. Should autoattach have failed in that case? (ie, is the system using service level 'self support' and there are no subcriptions that match?)

**Comment by alikins** [comment]
re cancel:

In theory, it's not going back to the previous screen. It should be sending you back to whatever would be the first screen in the current state. 

If you have not registered, it will send you back to choose_server. If you have registered, it will send you to select_sla or confirm_sla (or done screen with an error if it cant attach).

(ie, it sends you back to the start screen, but the start screen may decide to send you elsewhere)

**Comment by alikins** [comment]
re cancel button

Thoughts on what 'cancel' should do?

Would 'start over' be more accurate? (ignore string freeze issues)

I'd say, add both. But then 'cancel' doesn't make any sense, since I don't think it
will actually stop any already started actions (and there is no concept of undoing or rolling
back those changes).

I think with current code, it should be relatively close to supporting 'back', but there are a lot of
weird cases to handle for 'back' to DWALSM[1] that are error prone. (for, back from 'select_sla' to 
credentials... should that unregister? only unregister if the credentials change?)

[1] Do What At Lest Somone Means

**Comment by cnsnyder** [comment]
re redbar: I don't believe it should fail in that case as I was using an employee subscription
re cancel button: start over would probably be more accurate. I think that "cancel" should cancel what is being done presently.

Wrt either of the above issues, I believe they should be addressed in a separate PR.

**Pull request merged**
