### PR TITLE
2101510: [1.28] Fix D-Bus Register() and update entitlement certs

### PR DESCRIPTION
**Pull request by jirihnidek**
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2101510
* Backport of PR #3080
  * It wasn't possible to do simple cherry-pick
* Card ID: ENT-5185
* When D-Bus method Register() was called with argument
  enable_content == True and entitlement mode was used, then
  entitlement certificates were not installed on the system
* Added several unit tests

### CODE REVIEW

**Comment by jirihnidek** [comment]
There are some issues with unit tests. I will fix them...

**Comment by jirihnidek** [comment]
The failed CI jobs is related to `rpmlint`. It seems that this commit has to be backported:

https://github.com/candlepin/subscription-manager/commit/4af3f18f50c2e30090f7ae28df2e8e45c695348c

We use Fedora 35 and it seems that the current `rpmlint` does not support `--file` CLI option anymore. I would like to backport this change in different PR.

**Comment by ptoscano** [comment]
> The failed CI jobs is related to `rpmlint`. It seems that this commit has to be backported:
> 
> [4af3f18](https://github.com/candlepin/subscription-manager/commit/4af3f18f50c2e30090f7ae28df2e8e45c695348c)
> 
> We use Fedora 35 and it seems that the current `rpmlint` does not support `--file` CLI option anymore. I would like to backport this change in different PR.

Yes please. I'm curious to know whether that commit is enough, or more commits from `main` are needed. Let's start with that one :)

**Comment by jirihnidek** [comment]
It looks like that #3121 fixes the issue with rpmlint.

**Review by ptoscano — APPROVED** [review]
Plain backport, LGTM -- thanks!

**Pull request merged**
