### PR TITLE
1934312: facts discrepancy between cpu.cpu_socket(s) and lscpu.socket(s)

### PR DESCRIPTION
**Pull request by tlhmerry9**

### CODE REVIEW

**Review by ptoscano — CHANGES_REQUESTED** [review]
@tlhmerry9 please explain, either as comment in the code or in the commit message, why the change was done; right now it is a bit scarce of details, and I do not understand why it is needed at all

Regardless, please amend the commit message to say this is specific to aarch64, so it is easier to read/filter while browsing the commit log.

**Review by ptoscano — CHANGES_REQUESTED** [review]
> For aarch64 the socket_count = cpu_count and should not use the following
> calculation:  socket_count = cpu_count // cores_per_socket // threads_per_core

This is a good starting point, however it misses an important detail: the "why".
- why is the non-s390x formula not working / not good enough?
- how is the situation compared to the other architectures?
- why was this solution chosen in particular?

Small hint: imagine yourself reading your own commit message in the future, let's say in 1 year or even longer. Make sure that the commit message describes enough so you can understand, just by reading it, what was the problem that required a change, and why that particular fix/change was done.

**Review by ptoscano — CHANGES_REQUESTED** [review]
The explanation is improving indeed, however it still misses an explanation on why the calculation is wrong on aarch64. Before this line, there is a semi-complex logic to determine `socket_count`, `cpu_count`, `cores_per_socket`, and `threads_per_core`, so we need to know exactly how that logic is providing a wrong calculation on aarch64.

Can you please provide the output of the following commands?
```sh
$ grep '' /sys/devices/system/cpu/cpu*/topology/thread_siblings_list
$ grep '' /sys/devices/system/cpu/cpu*/topology/core_siblings_list
```

**Comment by jsefler** [comment]
Like Pino, I would also would like to know the "why" before accepting this merge.  Why is there a discrepancy in the lscpu and the cpu fact?  I know that I opened the bugzilla, but I am not confident what is the right value for the fact should be.

**Comment by tlhmerry9** [comment]
> Like Pino, I would also would like to know the "why" before accepting this merge. Why is there a discrepancy in the lscpu and the cpu fact? I know that I opened the bugzilla, but I am not confident what is the right value for the fact should be.

I am building a beaker system, which is queued and is taking time.  I also reached out to Rich Jerrido, and once the beaker system is finished, I want him to look and give feedback before I update the commit message

**Comment by tlhmerry9** [comment]
`[root@hpe-apollo-cn99xx-14-vm-07 subscription-manager]# grep '' /sys/devices/system/cpu/cpu*/topology/thread_siblings_list
/sys/devices/system/cpu/cpu0/topology/thread_siblings_list:0
/sys/devices/system/cpu/cpu1/topology/thread_siblings_list:1
/sys/devices/system/cpu/cpu2/topology/thread_siblings_list:2
/sys/devices/system/cpu/cpu3/topology/thread_siblings_list:3
`
`[root@hpe-apollo-cn99xx-14-vm-07 subscription-manager]# grep '' /sys/devices/system/cpu/cpu*/topology/core_siblings_list
/sys/devices/system/cpu/cpu0/topology/core_siblings_list:0-3
/sys/devices/system/cpu/cpu1/topology/core_siblings_list:0-3
/sys/devices/system/cpu/cpu2/topology/core_siblings_list:0-3
/sys/devices/system/cpu/cpu3/topology/core_siblings_list:0-3
`

**Comment by tlhmerry9** [comment]
This should be closed in favor of https://github.com/candlepin/subscription-manager/pull/2719

**Pull request closed without merging**
