### PR TITLE
feat: Remove 'addons' subcommand(s)

### PR DESCRIPTION
**Pull request by m-horky**
* Card ID: CCT-592

### CODE REVIEW

**Review by jirihnidek — APPROVED** [review]
LGTM

**Comment by jirihnidek** [comment]
@m-horky please resolve conflicts in man page. Otherwise, it looks good.

**Review by DuckBoss — APPROVED** [review]
Thanks for the PR, LGTM too. Let's get this pre-verified. :+1:

**Review by ptoscano — APPROVED** [review]
thanks!

**Pull request merged**
