### PR TITLE
1448313: Do not log error, when rhsmcertd is restarted

### PR DESCRIPTION
**Pull request by jirihnidek**
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1448313#c9
* Another case, when rhsmcertd is restarted

### CODE REVIEW

**Comment by jirihnidek** [comment]
I suspect some problems, when such logic would be inside method `def _read_cache(self)`, because error messages could be expected in some situation. Thoughts?

**Comment by kahowell** [comment]
> I suspect some problems, when such logic would be inside method def _read_cache(self), because error messages could be expected in some situation. Thoughts?

I think as long as only debug log for the special-case of non-existent cache file and keep the rest of the logic the same, it shouldn't cause issues.

**Comment by kahowell** [comment]
@jirihnidek looks good. Please squash before merge.

**Comment by jirihnidek** [comment]
@kahowell squashed, commited and force pushed

**Pull request merged**
