### PR TITLE
Allow to write syspurpose file

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by ptoscano** [comment]
Hello @sbernhard,

while the change seems (at least at a quick glance) mostly OK, can you please describe the situation/scenario that this bug caused? This way, it is easier to reproduce the issue and validate that your fix works and has no side effects. Thanks!

**Comment by sbernhard** [comment]
If syspurpose is not built (INCLUDE_SYSPURPOSE=0) the syspurpose check is false and therefore it tries to write the local syspurpose file. But the file is opened as read only and therefore it failed

**Comment by ptoscano** [comment]
> If syspurpose is not built (INCLUDE_SYSPURPOSE=0)

Note that the standalone syspurpose tool exists last in 1.28, and no more in current main. Hence, please try to reproduce it with the syspurpose subcommand of subscription-manager.

> the SyncedStore variable check is false

Which check exactly in the SyncedStore class?

Can you please provide a scenario / sequence of commands / etc so that I can reproduce the issue?

**Comment by sbernhard** [comment]
If you disable INCLUDE_SYSPURPOSE and Lazer on you run sub-man, in line 23 the SyncedStore is included which fails if you disable syspurpose.

Therefore, the check in line 106 fails and it tries to write the file.

Other than that, of you want to write something and the file is opened in read only mode, it will fail - it doesn't matter which scenario it is. It's wrong I think 😃

**Comment by sbernhard** [comment]
@ptoscano this is mainly because of the debian version of the subscription-manager which we build and provide as OSS at http://apt.atix.de/

**Comment by sbernhard** [comment]
ping

**Comment by ptoscano** [comment]
Sorry for the late answer, Christmas/new year holidays started, and then other work piled up. I didn't forget about it, though :)

From what I can see, the situation you describe may happen only in sub-man < 1.29 (i.e. in the branch `subscription-manager-1.28` and older ones). In `main`, `SyncedStore` is included unconditionally, as all the syspurpose bits were merged together with the "subscription-manager" Python module instead of being an own module and own command line tool (`syspurpose`). Hence, from the POV of `main`, all the code paths for `SyncedStore == None` are dead paths, as they cannot be triggered anymore.

Regarding the `subscription-manager-1.28`: due to the backports we did for the unified syspurpose command in subscription-mananger, there were no added checks for `SyncedStore`. This means that in that branch building with `INCLUDE_SYSPURPOSE=0` will create broken syspurpose commands. The possible options I see are:

1. add more fixes to make the `INCLUDE_SYSPURPOSE=0` case still working, at the cost of either disable some subcommands or make them less functional, and on top of this add the changes of this MR; this would mean to maintain more code specific in 1.28, and potentially breaking in the future (since backports from `main` could create again unchecked usages of `SyncedStore`)
2. tweak the `INCLUDE_SYSPURPOSE=0` to not exclude the "syspurpose" Python module anymore, only the `syspurpose` command line tool (and the files)
3. drop `INCLUDE_SYSPURPOSE=0` altogether, always shipping all the syspurpose stuff (Python module, `syspurpose` tool, files)

Personally I'd lean toward options (2) and (3), as (1) seems mostly untested (from our POV).

Can you please clarify a bit more what your actual use case?

**Comment by sbernhard** [comment]
Well. Looks like, the best way to solve the problems together with "unsupported" INCLUDE_SYSPURPOSE=0 is, to remove it completely and clean up all the code in which INCLUDE_SYSPURPSE=0 would have been used.

**Comment by ptoscano** [comment]
@sbernhard not a problem either way; however, I'd like to know what are your use cases of INCLUDE_SYSPURPOSE=0, so we can try to get the best out of this :)

**Comment by ptoscano** [comment]
Hey @sbernhard,

getting back on this, as there was no followups, and I wanted to make sure to have no missed anything. Can you please describe what you use `INCLUDE_SYSPURPOSE=0` for? At this point it is basically broken in the 1.28 branch, so what I would do is getting rid of it altogether. If so, how would that impact you?

Thanks!

**Comment by sbernhard** [comment]
> Hey @sbernhard,
> 
> getting back on this, as there was no followups, and I wanted to make sure to have no missed anything. Can you please describe what you use `INCLUDE_SYSPURPOSE=0` for? At this point it is basically broken in the 1.28 branch, so what I would do is getting rid of it altogether. If so, how would that impact you?
> 
> Thanks!

Ah. Thanks for letting me know, that this PR is still open. I will close it because we are now building everything with enabled syspurpose.

My suggestion, we should remove this option and everything related to INCLUDE_SYSPURPOSE=0

**Comment by ptoscano** [comment]
> Ah. Thanks for letting me know, that this PR is still open. I will close it because we are now building everything with enabled syspurpose.

No problem!

> My suggestion, we should remove this option and everything related to INCLUDE_SYSPURPOSE=0

Agree: see the PR #3021 that I just created.

**Pull request closed without merging**
