### PR TITLE
1243704: Goto error screen on 'cancel'

### PR DESCRIPTION
**Pull request by alikins**
For initial-setup, error screen is also the choose server
screen.

If we finish, and are "done", hide the cancel and register
buttons.

### CODE REVIEW

**Comment by wottop** [comment]
Does not show option to register regardless of system state.

(__main__.py:30078): Gtk-CRITICAL **: gtk_box_reorder_child: assertion 'old_link != NULL' failed

**Comment by alikins** [comment]
syslog/journtcl messages from initial-setup?

And/or add the following to the end of the init() method at the end of 
/usr/lib/python2.7/site-packages/initial_setup/initial_setup_log.py:

```
    log = logging.getLogger("")
    log.setLevel(logging.DEBUG)
    stream_format_string = "%(asctime)s %(threadName)s [%(name)s @%(filename)s:%(funcName)s:%(lineno)d ]  - %(message)s"
    stream_formatter = logging.Formatter(stream_format_string)
    stream_handler = logging.StreamHandler()
    stream_handler.getLevel(logging.DEBUG)
    stream_handler.setFormatter(stream_formatter)
    log.addHandler(stream_handler)
```


And then post the console output

**Comment by wottop** [comment]
[wpoteat@dhcp137-134 subscription-manager]$ sudo initial-setup 
2015-07-31 12:52:27,915 MainThread [initial-setup @__main__.py:<module>:28 ]  - display mode detected: gui
2015-07-31 12:52:27,916 MainThread [initial-setup @__main__.py:<module>:36 ]  - GI overrides imported
2015-07-31 12:52:27,916 MainThread [initial-setup @__main__.py:<module>:54 ]  - found 3 addon modules:
2015-07-31 12:52:27,916 MainThread [initial-setup @__main__.py:<module>:56 ]  - ks
2015-07-31 12:52:27,917 MainThread [initial-setup @__main__.py:<module>:56 ]  - spokes
2015-07-31 12:52:27,917 MainThread [initial-setup @__main__.py:<module>:56 ]  - categories
2015-07-31 12:52:27,917 MainThread [initial-setup @__main__.py:<module>:59 ]  - initializing the Anaconda log
2015-07-31 12:52:27,919 MainThread [initial-setup @__main__.py:<module>:66 ]  - initializing threading
2015-07-31 12:52:27,919 MainThread [initial-setup @__main__.py:<module>:71 ]  - initializing network logging
2015-07-31 12:52:27,999 MainThread [initial-setup @__main__.py:<module>:95 ]  - parsing input kickstart /root/anaconda-ks.cfg
2015-07-31 12:52:28,052 MainThread [initial-setup @__main__.py:<module>:100 ]  - kickstart parsing done
2015-07-31 12:52:28,052 MainThread [initial-setup @__main__.py:<module>:108 ]  - trying to import GUI
2015-07-31 12:52:28,502 MainThread [initial-setup @__main__.py:<module>:121 ]  - initializing GUI
2015-07-31 12:52:28,503 MainThread [initial-setup @__main__.py:<module>:135 ]  - setting up the UI
2015-07-31 12:52:28,643 MainThread [anaconda @common.py:collect:628 ]  - Failed to import module in collect: No module named categories.system
2015-07-31 12:52:28,643 MainThread [initial-setup @__main__.py:<module>:139 ]  - starting the UI

(__main__.py:16945): Gtk-CRITICAL **: gtk_box_reorder_child: assertion 'old_link != NULL' failed
2015-07-31 12:52:28,738 MainThread [anaconda @common.py:collect:628 ]  - Failed to import module in collect: No module named categories.system
2015-07-31 12:52:28,831 MainThread [initial-setup @eula.py:initialize:39 ]  - initializing the EULA spoke
2015-07-31 12:52:28,831 MainThread [initial-setup @eula.py:initialize:48 ]  - looking for the license file
2015-07-31 12:52:28,833 MainThread [initial-setup @eula.py:initialize:59 ]  - opening the license file

**Comment by wottop** [comment]
I accepted the license,when back to the initial page and clicked configure

2015-07-31 12:53:18,311 MainThread [initial-setup @eula.py:on_check_button_toggled:100 ]  - license is now accepted
2015-07-31 12:53:29,847 MainThread [initial-setup @__main__.py:<module>:161 ]  - executing kickstart
2015-07-31 12:53:29,847 MainThread [initial-setup @__main__.py:<module>:165 ]  - skipping <pyanaconda.kickstart.Keyboard object at 0x3a8ef50> on line 13
2015-07-31 12:53:29,847 MainThread [initial-setup @__main__.py:<module>:165 ]  - skipping <pyanaconda.kickstart.Lang object at 0x3a989d0> on line 15
2015-07-31 12:53:29,847 MainThread [initial-setup @__main__.py:<module>:165 ]  - skipping <pyanaconda.kickstart.Timezone object at 0x3a98610> on line 23
2015-07-31 12:53:29,850 MainThread [initial-setup @__main__.py:<module>:179 ]  - executing <pyanaconda.kickstart.Group object at 0x3a980d0> on line 0
2015-07-31 12:53:29,850 MainThread [initial-setup @__main__.py:<module>:177 ]  - skipping <pyanaconda.kickstart.User object at 0x3a988d0> on line 24
2015-07-31 12:53:29,851 MainThread [initial-setup @__main__.py:<module>:177 ]  - skipping <pyanaconda.kickstart.RootPw object at 0x3a98210> on line 21
2015-07-31 12:53:29,851 MainThread [initial-setup @__main__.py:<module>:183 ]  - executing addons
2015-07-31 12:53:29,852 MainThread [initial-setup @__main__.py:<module>:187 ]  - writing the Initial Setup kickstart file /root/initial-setup-ks.cfg
2015-07-31 12:53:29,863 MainThread [initial-setup @__main__.py:<module>:190 ]  - finished writing the Initial Setup kickstart file

**Comment by alikins** [comment]
Sounds like an old version of initial-setup.
Our module needs the 7.2 version after 0.3.9.24-1, but latest rhel7.2 version is better.

**Comment by wottop** [comment]
ack

**Pull request merged**
