### PR TITLE
1472746: Correct sorting of dates in subman gui

### PR DESCRIPTION
**Pull request by jirihnidek**
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1472746

### CODE REVIEW

**Comment by jirihnidek** [comment]
[Bug 1472746 - GUI: Cannot sort My Subscriptions Tab by end date](https://trello.com/c/XIj5P6b6/496-bug-1472746-gui-cannot-sort-my-subscriptions-tab-by-end-date)

**Comment by kahowell** [comment]
retest this please

**Comment by wottop** [comment]
Ack functionality

**Comment by wottop** [comment]
good to go.

**Pull request merged**
