### PR TITLE
1516439: Cockpit reports error during unregister when candlepin unavailable

### PR DESCRIPTION
**Pull request by jirihnidek**
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1516439

### CODE REVIEW

**Comment by jirihnidek** [comment]
I will do proper implementation of this, when #1727 will be merged to master.

**Comment by kahowell** [comment]
> I will do proper implementation of this, when #1727 will be merged to master.

Should we hold off on reviewing until then?

**Comment by jirihnidek** [comment]
@kahowell yes please

**Comment by jirihnidek** [comment]
[Bug 1489521 - subscription-manager-cockpit - no feedback when deregistering a system and a server is down](https://trello.com/c/RE1DMRYY/675-bug-1489521-subscription-manager-cockpit-no-feedback-when-deregistering-a-system-and-a-server-is-down)

**Comment by jirihnidek** [comment]
@kahowell it is ready for PR review.

**Comment by jirihnidek** [comment]
@kahowell the commit was message amended.

**Pull request merged**
