### PR TITLE
Polished changes provided in #1816 and added one unit test

### PR DESCRIPTION
**Pull request by jirihnidek**
The patch for BZ bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=1576423 was provided in this PR: #1816. This is only polishing of original patch.

### CODE REVIEW

**Comment by jirihnidek** [comment]
retest this please

**Comment by jirihnidek** [comment]
retest this please

**Comment by wottop** [comment]
I see the polish, but I think you forgot to commit the unit test.

**Comment by jirihnidek** [comment]
@wottop unit test added.

**Comment by wottop** [comment]
ack

**Pull request merged**
