### PR TITLE
Adding debian / ubuntu package build instructions

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by sbernhard** [comment]
Work started by @mdellweg, @quba42, @m-bucher

**Comment by cnsnyder** [comment]
@candlepin-bot Ok to test

**Comment by sbernhard** [comment]
How to continue with this @cnsnyder ?

**Comment by cnsnyder** [comment]
@candlepin-bot please retest this

**Comment by cnsnyder** [comment]
@sbernhard There were some failing tests on our CI system. I'm rerunning the tests as I believe them to be transient failures. If they're not I'll provide you with details on the issues so we can work together to solve them.
Thank you for working with me on this!

**Comment by cnsnyder** [comment]
@candlepin-bot please retest this

**Comment by bkearney** [comment]
@cnsnyder ow goes the review on this PR.

**Comment by cnsnyder** [comment]
@bkearney We keep experiencing failing tests. Details forthcoming (keep losing builds)

**Comment by cnsnyder** [comment]
@candlepin-bot please retest this

**Comment by sbernhard** [comment]
Thanks @cnsnyder

**Comment by BloodyIron** [comment]
Does this mean subscription-manager-1.26.2-1 can enable Ubuntu to be managed by Foreman via Katello now, or what? I can't tell since I can't find Release Notes for subscription-manager (can we change that?).

**Comment by BloodyIron** [comment]
So almost one year later and nobody has responded to my question?

**Comment by sbernhard** [comment]
We (ATIX AG) are about to release built debian / ubuntu packages soon. Give us some more days (5?)

**Comment by BloodyIron** [comment]
> We (ATIX AG) are about to release built debian / ubuntu packages soon. Give us some more days (5?)

Nice! Will that be in a PPA or what?

**Comment by quba42** [comment]
@BloodyIron More likely it will simply be a publicly hosted repository on an ATIX webserver, but that should not make a big difference.

**Pull request merged**
