### PR TITLE
1440251: Fix building of rhsmcertd at RHEL

### PR DESCRIPTION
**Pull request by jirihnidek**
When I tried to build subscription_manager at CentOS 7, then building of src/daemons/rhsmcertd.c failed. The main reason is absence of SYS_getrandom or getrandom() at systems with kernel < 3.17.0. More details are in this bug report:

https://bugzilla.redhat.com/show_bug.cgi?id=1440251

I just added simple fix. May be, it would be better to seed pseudo-random generator with something like this:

```c
unsigned int seed;
FILE* urandom = fopen("/dev/urandom", "r");
fread(&seed, sizeof(unsgined int), 1, urandom);
fclose(urandom);
srand(seed);
```

BTW: semicolon at the end of definition is not good idea. All random generating was IMHO useless. Do not ignore warnings :-).

### CODE REVIEW

**Comment by cnsnyder** [comment]
Great catches! I think the solution mentioned in your comment (of reading from "/dev/urandom" for the seed) would be preferable as to seeding using the time. The use case for the random offset is to prevent a multitude of virtual machines, all restarted at the same (or similar) time from causing peak load on the connected satellite (see RFE BZ [1435013](https://bugzilla.redhat.com/show_bug.cgi?id=1435013]). Seeding using time then results in less actual splay (for those that are synced using ntp for example)

**Comment by cnsnyder** [comment]
Also, as a part of the process for bug fixes and rfes, we like to add the PR as an external tracker to the bugzilla bug.

In the external trackers section on bugzilla there is a drop down menu (initially set to '--do not add--'). Click on that tracker then find the option named 'Github'. The value you need to place in the 'Bug id' box is the url of the the PR less the protocol and hostname. For example the "bug id" of this PR would be "candlepin/subscription-manager/pull/1579".

**Comment by cnsnyder** [comment]
On final addition to the process, upon completion of review, generally speaking, we squash the commits that fix the bug down to one and begin the commit message with the bug number being fixed followed by a colon. ('1440251: ...')

**Comment by jirihnidek** [comment]
@cnsnyder, I modified this pull request to use /dev/urandom (more details are in commit log). I squashed commits into one commit and I added number of BZ report at beginning of commit message. I also modified bug report at BZ as you suggested.

Still scared of git push --force :-)

**Comment by cnsnyder** [comment]
Looks great to me! Thanks again!

**Pull request merged**
