### PR TITLE
1330036: Better status error message for initial-setup

### PR DESCRIPTION
**Pull request by jirihnidek**
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1330036
* It seems that argument `exc_info` is not used for anything
  useful. I decided to use it for passing error_code.
* Screenshot of initial-setup with new error message:

initial-setup_registered_with_auto-attach_failed

### CODE REVIEW

**Comment by jirihnidek** [comment]
[Bug 1330036 - Initial-setup : A message "Error during registration" when system is registered successfully but auto-attach failed due to installed products not being covered by a single service-level](https://trello.com/c/0GOTL8Xj/495-bug-1330036-initial-setup-a-message-error-during-registration-when-system-is-registered-successfully-but-auto-attach-failed-due)

**Comment by wottop** [comment]
I think the message for an auto-attach deficiency should be the regular 'system x registered'. The last screen on the spoke reports auto-attach issues. The message you propose is somewhat informative, but the user cannot remedy the situation from initial-setup. If they don't auto-attach from initial-setup, they are still not compliant, but also don't get the message. 

The 'system x registered message ' is correct and I think should be the state reported.

**Comment by jirihnidek** [comment]
It is not problem to change message under "Subscription Manager" to something else. It can be standard "System x successfully registered", but I agree with Shwetha that the issue should be reported somehow at main page of initial-setup too. What about different color of message?.
 
BTW: The user get very informative (but little bit confusing) message at bottom of this page: https://bugzilla.redhat.com/attachment.cgi?id=1150398. It could be little bit confusing, because initial-setup does not have "All Available Subscriptions" tab. Such message is there, because this part of code is shared with subman-gui.

**Comment by jirihnidek** [comment]
Anaconda guidelines [1] are not too specific about content of message bellow the spoke's title: "An additional property called **status** exists; this property contains a single line of text with a short summary of configured values".

I thought it is possible to change color of **status**, but the color is influenced by properties: `ready`, `completed` and `mandatory`. Thus reporting this issue using different color of **status** is not possible.

We can wait for @kahowell's and @mstead's opinion and then make some consensus, OK?

[1] http://rhinstaller.github.io/anaconda-addon-development-guide/sect-anaconda-addon-gui-support.html

**Comment by kahowell** [comment]
So here are my thoughts:

1. The purpose of the initial-setup plugin is a convenience. The purpose as an initial-setup plugin is to offer minimum functionality needed to register and attach during installation; we don't need to cover all use cases, as the user can use subscription-manager or subscription-manager-gui once they're in the installed system.

2. The plugin's messages centered around registration, and not attachment. We would like the user to register; attachment is optional (during the initial setup).

> the issue should be reported somehow at main page of initial-setup too

I disagree. Let's keep the main page about registration status, and nothing more.

> What about different color of message?

Let's special-case for initial-setup, and let's change from an error to a warning if possible. I'd prefer: "You will need to use Red Hat Subscription Manager to manually attach subscriptions to this system after completing setup." in place of any reference to the "All Available Subscriptions" tab. This is close to what we use already for manual attach in firstboot.

**Comment by jirihnidek** [comment]
@kahowell @wottop Thanks for review. Keeping main page about registration status makes sense. I will do proposed changes.

**Comment by wottop** [comment]
@kahowell @jirihnidek Looks good to me
ack

**Pull request merged**
