### PR TITLE
Fix apt-plugin for subscription-manager

### PR DESCRIPTION
**Pull request by m-bucher**
I should do more python programming :wink:

introduced with #2226

### CODE REVIEW

**Comment by m-bucher** [comment]
Currently experiencing some problems using python2 with this script.
Let me check this again, I might have additional changes

**Comment by jirihnidek** [comment]
@candlepin-bot ok to test

**Comment by jirihnidek** [comment]
@m-bucher is your PR ready for review ATM?

**Comment by m-bucher** [comment]
> @m-bucher is your PR ready for review ATM?

Yes, the problem I mentioned should be fixed in the current state.

**Pull request merged**
