### PR TITLE
ENT-4370: Drop old dbus_interface.py

### PR DESCRIPTION
**Pull request by m-horky**
* Card ID: ENT-4370

- DBus name com.redhat.SubscriptionManager is no longer used.
- The injection was added in 2013 (0a95a84, 43f86b8) for old Anaconda
setup.

### CODE REVIEW

**Comment by ptoscano** [comment]
Since it used to be used in Anaconda, maybe a quick check there that is not used anymore would be good IMHO.

What about the occurrency of `inj.DBUS_IFACE` in src/subscription_manager/cli_command/cli.py?

**Comment by m-horky** [comment]
I must have missed that, thanks. I've tracked that line back to 2013 and to the com.redhat.SubscriptionManager DBus name, so it should be safe to remove it, too, as it can't have any effect now.

**Review by ptoscano — APPROVED** [review]
+0 −94 -- nice!

**Comment by ptoscano** [comment]
Side quest: it looks like `get_status_for_icon()` and the associated constant values for it in src/subscription_manager/cert_sorter.py are unused.

**Pull request merged**
