### PR TITLE
1365472: Add keyboard mnemonics for initial-setup

### PR DESCRIPTION
**Pull request by kahowell**
This essentially boiled down to adding mnemonics for register GUI in
GTK3. Also did the same for GTK2.

### CODE REVIEW

**Comment by wottop** [comment]
Have you checked to make sure that the change in these strings does not adversely affect the translation?

**Comment by wottop** [comment]
Otherwise, the tab stops are working as expected.

**Comment by kahowell** [comment]
This will definitely need some translation work (since the mnemonics will need to be localized). Is that what you were asking?

**Comment by wottop** [comment]
Concerns about translations eased. Will need to confirm tab stops in other languages in testing.

ACK

**Pull request merged**
