### PR TITLE
1844508: subscription-manager should send its version in the User-Age…

### PR DESCRIPTION
**Pull request by wottop**
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1844508
* Added version into User-agent header
* Improvements of setting client version in HTTP request
* Added **kwargs to BaseConnection. Thus it was possible to add
  client_version keyed argument to call of ContentConnection()
  and UEPConnection()
* Added several unit tests

### CODE REVIEW

**Comment by jirihnidek** [comment]
The http headers could look like this:
```json
{
    "Content-type": "application/json",
    "Accept": "application/json",
    "x-subscription-manager-version": "RPM_VERSION",
    "Accept-Language": "cs-cz",
    "X-Correlation-ID": "70859bc7ffbd4f0b836a7c1b2946414a",
    "User-Agent": "RHSM/1.0 (cmd=rhsm_service.py) subscription-manager/RPM_VERSION dbus_sender=cockpit-bridge",
    "Content-Length": "0"
}
```

**Comment by cnsnyder** [comment]
Looks good to me (pending passing tests on CI, tests pass for me locally).

**Comment by cnsnyder** [comment]
The tests have failed, but for CI infrastructural reasons. I think these tests will pass once the following is merged: https://github.com/candlepin/candlepin-jobs/pull/56.

**Comment by jirihnidek** [comment]
@candlepin-bot retest this please

**Pull request merged**
