### PR TITLE
Awood/test fix

### PR DESCRIPTION
**Pull request by awood**
Fix our tests to run independently from each other.  Test using the [nose-randomly plugin](https://pypi.python.org/pypi/nose-randomly) which can be installed with `pip install -r test-requirements.txt` and used with `nosetests --with-randomly`

### CODE REVIEW

**Comment by awood** [comment]
No clue how to fix these Jenkins errors.  The stylish one is complaining about Python 2.5 compatibility which we don't do anymore and the nosetests builder is failing due to some UTF8 characters in the code.  Perhaps the Jenkins locale isn't a UTF8 one?  They run fine on my system.

**Comment by cnsnyder** [comment]
I'm seeing the same stylish issues on another PR I just opened. Seems rather bizarre. I wonder if something in our jenkins environment changed.

**Comment by awood** [comment]
> I'm seeing the same stylish issues on another PR I just opened. Seems rather bizarre. I wonder if something in our jenkins environment changed.

The pyqver2 library that we use added flake8 integration so all those checks are run as part of flake8 now and show up as failures.  Previously pyqver2 was running as a separate build step and we were filtering spurious warnings.

**Comment by awood** [comment]
The bad thing about the nose-randomly plugin is that having it installed currently breaks the nose integration with setuptools.  See https://github.com/adamchainz/nose-randomly/issues/11

So we'd need to change the Jenkins scripts to run `nosetests` instead of `./setup.py nosetests`.  Not a big deal but not something I feel like doing in this PR.

**Comment by awood** [comment]
> The issue is that all PRs that don't have the nose-randomly plugin listed in their requirements will fail because Jenkins will need to provide the --randomly-seed=PR# argument on the command line (there's no option for using an environment variable) which won't be recognized in other PRs.

I think this shouldn't be a problem actually since most of the build steps are not in Jenkins at all but instead in the Makefile in the branch.

**Comment by cnsnyder** [comment]
Works for me! Looks good.

**Pull request merged**
