### PR TITLE
Clang fixes

### PR DESCRIPTION
**Pull request by tstellar**
This fixes a few errors that are uncovered when compiling with clang.

### CODE REVIEW

**Comment by jirihnidek** [comment]
@candlepin-bot ok to test

**Comment by tstellar** [comment]
> Hi, thanks for the PR. Overall your PR looks good. I have two small requests.
> 
> 1. Can you please squash commits into one commit?
Ok, done.

> 2. Can you please add some documentation about using clang for compiling product-id plugin?
Sure, where would you like me to put this documentation?
> 
> BTW: why do you want to compile our plugin using clang compiler?

We are working on a project to build all of Fedora with clang.  We think the entire Fedora package set will be a great test case for clang to help us catch regressions and find missing features.  We also think this will be beneficial for the Fedora packages, since clang may catch some warnings (which have the potential to be bugs) that gcc does not .

**Comment by jirihnidek** [comment]
> > Hi, thanks for the PR. Overall your PR looks good. I have two small requests.
> > 
> > 1. Can you please squash commits into one commit?
> >    Ok, done.
Thanks

> 
> > 1. Can you please add some documentation about using clang for compiling product-id plugin?
> >    Sure, where would you like me to put this documentation?
Please here: https://github.com/candlepin/subscription-manager/blob/master/src/dnf-plugins/product-id/README.md

> > 
> > BTW: why do you want to compile our plugin using clang compiler?
> 
> We are working on a project to build all of Fedora with clang. We think the entire Fedora package set will be a great test case for clang to help us catch regressions and find missing features. We also think this will be beneficial for the Fedora packages, since clang may catch some warnings (which have the potential to be bugs) that gcc does not .

Thanks you for info. Yeah, it make sense.

**Comment by jirihnidek** [comment]
@tstellar Friendly reminder. :smiley: Please can you update this PR and add requested information about building product-id using clang to README.md? Thanks

**Comment by tstellar** [comment]
Thank you!

**Pull request merged**
