### PR TITLE
1928667: Added UTC to the last_boot fact (ENT-3566)

### PR DESCRIPTION
**Pull request by tlhmerry9**
Simple one line change

### CODE REVIEW

**Review by jirihnidek — COMMENTED** [review]
Hi, it looks OK. Would you try to create one simple unit test for this case?

**Comment by tlhmerry9** [comment]
> Hi, it looks OK. Would you try to create one simple unit test for this case?

A simple unit test:

$ vagrant up

$ vagrant ssh

$ cd /vagrant

$ sudo subscription-manager facts | grep last_boot
last_boot: 2021-03-03 13:32:59 UTC

**Comment by jirihnidek** [comment]
> > Hi, it looks OK. Would you try to create one simple unit test for this case?
> 
> A simple unit test:
> 
> $ vagrant up
> 
> $ vagrant ssh
> 
> $ cd /vagrant
> 
> $ sudo subscription-manager facts | grep last_boot
> last_boot: 2021-03-03 13:32:59 UTC

Hi, this is smoke test and I smoke tested your change using something very similar.

Unit tests are located in directory `./test`. Unit tests for `rhsmlib.facts.hwprobe` module is located here:

https://github.com/candlepin/subscription-manager/blob/master/test/rhsmlib_test/test_hwprobe.py

**Review by jirihnidek — APPROVED** [review]
Thanks for the unit test. :+1: Please squash commits into one commit and than I will merge it to master branch. I squash commit using following commands:

```
# Do only soft reset (not hard reset)!
git reset --soft HEAD~<number of commits to be be squashed>
# Look at status if everything is as expected
git status
# Look at change you are going to commit
git diff --cached
# Do commit (you can reuse existing commit message)
git commit --reedit-message=<commit id of commit you like to modify>
```

**Pull request merged**
