### PR TITLE
1856832: add --org=ORG to the ROLE OPTIONS, USAGE OPTIONS and ADDONS …

### PR DESCRIPTION
**Pull request by tlhmerry9**
…OPTIONS of the subscription-manager man pages

### CODE REVIEW

**Comment by tlhmerry9** [comment]
Please go over the wording and provide feedback.

**Comment by tlhmerry9** [comment]
To Test:

man man/subscription-manager/subscription-manager.8

**Review by jirihnidek — COMMENTED** [review]
It looks good, but this change should go to the master first and then it should be cherry-picked to the 1.28 branch. I can merge it, but it will be necessary to create same PR for master. Not sure if we should do cherry pick for the master? @cnsnyder Thoughts?

**Comment by tlhmerry9** [comment]
Created ENT-3661 for this change to be against master

**Review by jirihnidek — APPROVED** [review]
ACK

**Pull request merged**
