### PR TITLE
icons: update app icon

### PR DESCRIPTION
**Pull request by jimmac**
- based on the updated GNOME style (see https://gitlab.gnome.org/GNOME/Initiatives/issues/2)
- provide a symbolic variant (B/W stencil for accessibility theme)

### CODE REVIEW

**Comment by jirihnidek** [comment]
@candlepin-bot ok to test

**Comment by cnsnyder** [comment]
@jimmac Thank you for the new icons! It looks like for the new icon to get into the build in the right location, we either need to rename the file /home/csnyder/devel/subscription-manager/src/subscription_manager/gui/data/icons/hicolor/scalable/apps/subscription-manager-symbolic.svg to /home/csnyder/devel/subscription-manager/src/subscription_manager/gui/data/icons/hicolor/scalable/apps/subscription-manager.svg.

Alternatively we could make a modification to ./setup.py. (Will try to put the suggestion inline as a diff, if not will come back and update comment)

**Comment by jimmac** [comment]
The -symbolic variant is a monochrome stencil variant of the app icon used for the accessibility theme and some other ocntexts and uses a nominal size of 16x16px. It goes to $PREFIX/share/icons/hicolor/symbolic/ prefix/size. It should not go into the scalable size due to the nominal size difference (scalable is 128x128px).

**Comment by jirihnidek** [comment]
@candlepin-bot ok to test

**Pull request merged**
