### PR TITLE
1450862: remove obsolete certiciates of golden ticket

### PR DESCRIPTION
**Pull request by jirihnidek**
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1450862
* When there was obsolete golden ticket(s), then it wasn't
  removed during register --force

### CODE REVIEW

**Comment by wottop** [comment]
Please correct commit comment spelling of certificates

**Comment by kahowell** [comment]
@jirihnidek, does this also address [bug 1450938](https://bugzilla.redhat.com/show_bug.cgi?id=1450938)? If so, please mark bug 1450938 as a duplicate of 1450862...

**Comment by wottop** [comment]
ack

**Comment by jirihnidek** [comment]
Sorry for typo in my commit log. I wrote the log in hurry to catch my train. Should I try to change it now, when it is merged to master?

**Pull request merged**
