### PR TITLE
1176219: Error out if bad proxy settings detected

### PR DESCRIPTION
**Pull request by kahowell**
Improves upon changes in 7ce6801fc1cc38edcdeb75dfb5f0d1f8a6398c68

 - make is_valid_server_info handle proxy settings
 - detect 407 (proxy auth) http errors in is_valid_server_info
 - treat exceptions during test_proxy_connection as failures

### CODE REVIEW

**Comment by kahowell** [comment]
Need to squash pre-merge. Missed an unused import. Doh!

**Comment by kahowell** [comment]
Still need to squash! Moved exception to python-rhsm in candlepin/python-rhsm#183.

**Comment by cnsnyder** [comment]
@candlepin/jenkins-bot Please retest this

**Comment by kahowell** [comment]
retest this please

**Pull request merged**
