### PR TITLE
Updated from System Type to Entitlement Type

### PR DESCRIPTION
**Pull request by waldirio**
Updating the information, from `System Type` to `Entitlement Type` on `subscription-manager list --consumed` or `subscription-manager list --available`

### CODE REVIEW

**Comment by cnsnyder** [comment]
@candlepin-bot ok to test

**Comment by cnsnyder** [comment]
@waldirio One request, could you prepend the bz number to the commit message? Our tooling looks for bugs at the beginning of commit messages.

**Comment by waldirio** [comment]
> @waldirio One request, could you prepend the bz number to the commit message? Our tooling looks for bugs at the beginning of commit messages.

Hey, let me know if this is enough.

Thank you!!

**Comment by jirihnidek** [comment]
@waldirio Hi, thanks for PR. Please squash last two commits into one. You can do it using e.g.:

```
git checkout 1717147_type
git reset --soft HEAD~2
git commit --reedit-message=89b9808c7cb148be2168bf3acc4ad8d793ddc526
git push --force origin 1717147_type
```

**Comment by jirihnidek** [comment]
Please ignore my last comment, because I just noticed now that PR has been already merged to master :-).

**Pull request merged**
