### PR TITLE
1246680: Report on command line when rhsm-debug cannot collect subscr…

### PR DESCRIPTION
**Pull request by wottop**
…iption details

### CODE REVIEW

**Comment by wottop** [comment]
retest this plese

**Comment by alikins** [comment]
Is it supposed to work against 2.0?  

If it's okay to skip it against 2.0, I'd say dont print, but log a more detailed message explaining it (especially if there is a more focused exception to catch there...)

**Comment by wottop** [comment]
Not really more detail. It ws designed for older candlepin systems that did not allow subscription retrieval. And now the newer ones don't allow it any more. The message is pretty much all we have.

**Comment by wottop** [comment]
Removed the subscriptions option altogether

**Comment by alikins** [comment]
See https://github.com/candlepin/subscription-manager/pull/1277 for a small pr for this pr

**Comment by Ceiu** [comment]
ACK

```
crog@dhcp129-111:~/devel/subscription-manager(wottop/1246680) $ sudo subscription-manager register --force
...
The system has been registered with ID: c1d4e6b2-9853-47c6-9c6e-cf80482c1464 
crog@dhcp129-111:~/devel/subscription-manager(wottop/1246680) $ sudo rhsm-debug system --subscriptions    
Wrote: /tmp/rhsm-debug-system-20150831-706557.tar.gz
crog@dhcp129-111:~/devel/subscription-manager(wottop/1246680) $ sudo rhsm-debug system --no-subscriptions 
Wrote: /tmp/rhsm-debug-system-20150831-340198.tar.gz

2015-08-31 12:41:03,706 [INFO] rhsm-debug:15587 @debug_commands.py:98 - The rhsm-debug options '--subscriptions' and '--no-subscriptions' have no effect now.
2015-08-31 12:41:09,340 [INFO] rhsm-debug:15592 @debug_commands.py:98 - The rhsm-debug options '--subscriptions' and '--no-subscriptions' have no effect now.
```

**Comment by Ceiu** [comment]
Should this maybe output to the console as well?

**Pull request merged**
