### PR TITLE
Fix Makefile use of $(PREFIX) and $(DESTDIR)

### PR DESCRIPTION
**Pull request by mdellweg**
While trying to wrap this up in a debian package, i thought, that we can use the PREFIX variable in a more standardized way along with the DESTDIR variable.

Think of DESTDIR being `/` or the location of the chroot you want to install in.
Think of PREFIX being `/usr/local/` or for packages `/usr/`.

I hope, i caught all paths here.
Ping: @kahowell

### CODE REVIEW

**Comment by kahowell** [comment]
ok to test

**Comment by mdellweg** [comment]
@kahowell Thanks for the heads up!
I chose `DESTDIR` because it is widely adopted in Makefile projects. A quick search reveals, that it is in fact a GNU coding standard: https://www.gnu.org/prep/standards/html_node/DESTDIR.html
Also it is suggested here: https://www.debian.org/doc/manuals/maint-guide/modify.de.html#destdir

**Comment by kahowell** [comment]
> I chose DESTDIR because it is widely adopted in Makefile projects. A quick search reveals, that it is in fact a GNU coding standard: https://www.gnu.org/prep/standards/html_node/DESTDIR.html
Also it is suggested here: https://www.debian.org/doc/manuals/maint-guide/modify.de.html#destdir

Ah, did not know that. `DESTDIR` is fine then. Sorry I did not search for it first. A rebase is all that's necessary then.

**Comment by mdellweg** [comment]
@kahowell rebased.
Somehow, the ci server seems unresponsive.

**Comment by kahowell** [comment]
> Somehow, the ci server seems unresponsive.

It was a Jenkins node out of disk space. It's been fixed now.

Thanks for the PR! :smile:

**Comment by mdellweg** [comment]
Thank you!

**Pull request merged**
