### PR TITLE
Merge python-rhsm into subscription-manager repo

### PR DESCRIPTION
**Pull request by kahowell**
Only commits actually unique to this PR are:
 - d01c6e3
 - fdb16a8

(but don't take my word for it 😄); In order to reduce this to actual changes, you can add the python-rhsm repo as a remote in order to see those commits in context:

    git remote add python-rhsm https://github.com/candlepin/python-rhsm

Then, I'd recommend examining with `gitk`, `tig`, or similar, and you can observe that 9cdc401 is from python-rhsm's master branch.

It looks like this (excuse crude ascii representation):

```
        fdb16a8 (merge commit)
      /                        \
908316a (subman master)     d01c6e3 (python-rhsm moved to subdir)
     |                          |
    ...                     9cdc401 (python-rhsm master)
```

Assuming we accept this PR:

- [ ] We should remember to push python-rhsm tags to this repo at some point too.

### CODE REVIEW

**Comment by awood** [comment]
This looks okay to me, but before we pull the trigger, have we done some scratch builds with tito in Koji to make sure that everything works smoothly?

**Comment by kahowell** [comment]
@awood, I have not... I'll try and report back with results.

**Comment by kahowell** [comment]
Here are the two scratch builds.
https://koji.fedoraproject.org/koji/taskinfo?taskID=17972198
https://koji.fedoraproject.org/koji/taskinfo?taskID=17972176

@barnabycourt, any reason to hold off, or should we merge?

**Comment by awood** [comment]
All good from my perspective.  @barnabycourt hit the merge button when you're ready.

**Comment by barnabycourt** [comment]
@kahowell The requirements.text is still referencing the external python-rhsm project

**Comment by barnabycourt** [comment]
@kahowell Also sub-man/test/smoke.sh is still referencing the parent path

**Comment by barnabycourt** [comment]
@kahowell In order to merge this needs to have the jenkins tests ready so that we don't lose nose, style, tito, checks for the python-rhsm code

**Comment by kahowell** [comment]
Updated, see `git diff fdb16a8 bc60f73`:
 - fixed `requirements.txt`
 - fixed `test/smoke.sh`

**Comment by kahowell** [comment]
retest this please

**Comment by kahowell** [comment]
@barnabycourt, our PR jobs are updated (see github status :smile:), anything else before we merge?

**Pull request merged**
