### PR TITLE
1862431: option validation error from unexpected config entry

### PR DESCRIPTION
**Pull request by wottop**

### CODE REVIEW

**Review by cnsnyder — APPROVED** [review]
Works great for me! The nose and stylish tests are failing for a reason which is blocking a proper run for this PR (see https://github.com/candlepin/candlepin-jobs/pull/56 for an attempted fix)

So consider this an ACK pending successful nose and stylish tests.

**Comment by jirihnidek** [comment]
@candlepin-bot please retest this

**Comment by jirihnidek** [comment]
@candlepin-bot retest this please

**Comment by jirihnidek** [comment]
@candlepin-bot retest this please

**Comment by jirihnidek** [comment]
@candlepin-bot retest this please

**Pull request merged**
