### PR TITLE
feat: Removed command "redeem" from subscription-manager

### PR DESCRIPTION
**Pull request by jirihnidek**
* Card ID: CCT-242
* Original change done by Martin Grünwald
* Removed command "redeem"
  * Removed all references from man page
  * Removed from bash completion script
  * Removed related unit tests

### CODE REVIEW

**Comment by ptoscano** [comment]
This is generally good; there are few more references to "redeem" to remove from the man page:
- the "REDEEM OPTIONS" section, which can be removed altogether
- the "REDEEMING EXISTING SUBSCRIPTIONS" section, which can be removed altogether

Thanks!

**Review by ptoscano — CHANGES_REQUESTED** [review]
(request changes as per my last comment)

**Comment by jirihnidek** [comment]
@ptoscano I updated the man page.

**Review by ptoscano — APPROVED** [review]
thanks!

**Pull request merged**
