### PR TITLE
Translation extraction

### PR DESCRIPTION
**Pull request by wottop**

### CODE REVIEW

**Comment by wottop** [comment]
this one will be messier, because of 2 changes:
 There was a refactoring of managercli which means a lot of line numbers changed.
 The format of the messages in the new files went from '%s' substitution to '{variable}' formatting.

**Comment by ptoscano** [comment]
Hi @wottop,

considering that we are using the Fedora Weblate instance, we can use it to avoid manual work on our side.
In particular, a Weblate addon available there is to update automatically the translations whenever the template is updated; it is called `Update PO files to match POT (msgmerge)`. I'd recommend enabling that instead, with the following two configuration bits:
- `Keep previous msgids of translated strings: enabled` -- this is the old msgid of string is kept, and translators can easily see what changed in the original message
- `Use fuzzy matching: enabled` -- this fills new msgids by trying to check for similar translations; it is very helpful to not retranslate messages from scatch in case very small parts of them (like a typo fix) change

Enabling the msgmerge Weblate addon means that the only manual action left is to update the `keys.pot` file on our side, and then never touch the translations manually anymore.

**Comment by wottop** [comment]
We will have to experiment a bit to ensure that your suggestions will allow it to be on auto-pilot.

My experience was that the fuzzy matching was *way* too permissible with what it would match. It only needed to match about 50% of the words in a phrase to make them equivalent.

Does this mean that we would not inspect the translations before they get merged into the upstream? So far I don't have the confidence in the translators to do this.

**Comment by ptoscano** [comment]
> The weblate msmerge kills the metadata strings that describe the substitution in use [i.e. python-format].

Does it? In other project I have not seen this. It would be bad for Weblate to do that, it causes problems when validating the strings (although it does not matter when compiling a translation file as .mo).

> My experience was that the fuzzy matching was way too permissible with what it would match. It only needed to match about 50% of the words in a phrase to make them equivalent.

Well, it depends. I cannot say about a percentage, but rather about how _close_ the strings are. Also note that, in any case, the result of fuzzy matching adds the fuzzy marker: this means a message is marked for inspection by translators, and it will not be written in compiled .mo files (at least by default; there is the option to add fuzzy strings, but it is hardly used and ought to not be used in usual deployments).

> I have a test branch on both ends available if you want to try it out and confirm whether these issues can be cleared up.

Definitely, happy to take a look.

**Pull request closed without merging**
