### PR TITLE
Add content access cert functionality to subman

### PR DESCRIPTION
**Pull request by kahowell**
Behavior changes:

 - update the entitlement data section of a content access cert anytime
   we update certs
 - maintain a cache (used in update query) of the content access data,
   especially timestamp
 - on any registration, check for entitlement certs (so that content
   access cert can be pulled in seamlessly)

### CODE REVIEW

**Comment by nguyenfilip** [comment]
retest this please

**Comment by nguyenfilip** [comment]
retest this please

**Comment by kahowell** [comment]
retest this please

**Comment by kahowell** [comment]
Made a few changes; namely:
 - if there is more than one content access cert, only query for updates once...
 - on refresh, remove content access cache
 - don't force update of content access ever, (refresh handles via removing content access cache)
 - fail gracefully if content access call fails.

**Comment by kahowell** [comment]
Note: default commit status for c0bb240 can be ignored.

**Comment by kahowell** [comment]
retest this please

**Comment by kahowell** [comment]
Rebased against master.

**Comment by kahowell** [comment]
@barnabycourt test failures appear to be unrelated. I've got fixes in #1537. Happy to incorporate those into this branch or just handle in separate PR.

**Comment by kahowell** [comment]
Changed to constants where appropriate, and to detect content access cert based on extension rather than product ID.

**Comment by kahowell** [comment]
retest this please

**Comment by kahowell** [comment]
Re: most recent test run, some of the failures are unrelated, I opened candlepin/python-rhsm#195 for that. I'm working through the others...

**Comment by kahowell** [comment]
See the (just added) change in test/stubs.py... This along with candlepin/python-rhsm#195 should fix all test issues.

**Comment by kahowell** [comment]
retest this please

**Comment by kahowell** [comment]
@cnsnyder, requested change made (went ahead and squashed this time).

**Pull request merged**
