### PR TITLE
Improve test/smoke.sh

### PR DESCRIPTION
**Pull request by alikins**
Actually check exit code of cli apps.
Add color.
Morem tests (rhsmcertd, rhsm-debug, rct)
Keep track of fails for a report.

Backup and restore of a systems config should be
more useful now.

Also make script return 1 for test failures.

### CODE REVIEW

**Comment by dgoodwin** [comment]
**Build Log**
*last 10 lines*

 ```
[...truncated 86 lines...]
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
IRC notifier plugin: Sending notification to: #candlepin
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Setting status of 29cee15fe21aaa8c4b71fc9a870024ad8ab5ae71 to FAILURE with url http://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/subscription-manager-nose-tests-pull-request-builder/371/ and message: 'Build finished.'
```

**Comment by wottop** [comment]
Many tests fail with the following

Error: cannot import name Versions

**Comment by alikins** [comment]
You have to compile the code before the tests pass. 
run 'make'

**Comment by wottop** [comment]
ack

**Pull request merged**
