### PR TITLE
Use new API of DNF

### PR DESCRIPTION
**Pull request by jirihnidek**
* When new DNF API is available then use it.
* Use cache file to store productid certificates, then dnf API doesn't load productid from repository nor cache. For this reason it is necessary to use own cache.
* Refactoring of reading cache files

### CODE REVIEW

**Comment by cnsnyder** [comment]
@jirihnidek What is remaining to get this working? It looks good (given a brief look)

**Comment by jirihnidek** [comment]
@cnsnyder I don't use the API correctly. I discussed it with Jaroslav and I need to call `repo.add_metadata_type_to_download('productid')` in different hook.

**Comment by cnsnyder** [comment]
@jirihnidek Aside from a squash this looks good. Do you have a BZ for this?

**Comment by cnsnyder** [comment]
@jirihnidek Going to squash and merge to get this into the next build.

**Pull request merged**
