### PR TITLE
Make x509 date parsing handle dates after 2049

### PR DESCRIPTION
**Pull request by kahowell**
`ASN1_TIME` and associated functions transparently handle both
`ASN1_UTCTIME` (< 2050) and `ASN1_GENERALIZEDTIME` (> 2050) values.

Actually, the `X509_get` functions we were using already return
`ASN1_TIME`, but due to the way the types in openssl work, they are
usable in UTCTIME functions as long as the underlying data is in
UTCTIME.

### CODE REVIEW

**Comment by martinpitt** [comment]
I'm triggering a rhel-8-2 cockpit test here, to see if it works or needs some adjustments. I suppose it's time now to switch CI from RHEL 8.1 to 8.2 now, as 8.1 is pretty much "done" from a development POV.

**Comment by martinpitt** [comment]
rhel-8-2 failed, I'll send a separate PR to fix that.

**Comment by jirihnidek** [comment]
@kahowell Thanks for PR. Is there any bug report for this issue?
I would like to have at least one unit test for certificate containing date after 2049. It will require to generate new certificate.

**Comment by kahowell** [comment]
Related bug report is https://bugzilla.redhat.com/show_bug.cgi?id=1789654 (they chose to work around in Satellite 6 in a different way).

**Pull request merged**
