### PR TITLE
Added check for /etc/oracle-release in hwprobe

### PR DESCRIPTION
**Pull request by michaelwholley**
We run Katello in an all Oracle Linux environment and hwprobe reports our boxes as Red Hat (it looks at /etc/redhat-release). I added a check along with the /etc/redhat-release to look for /etc/oracle-release instead.

### CODE REVIEW

**Comment by dgoodwin** [comment]
Can one of the admins verify this patch?

**Comment by michaelwholley** [comment]
I realized once I submitted this patch I didn't test it on a non-oracle distro. I just tested on CentOS and it doesn't work. Sorry. I guess I don't know enough Python to figure out how to do what I'm trying. I'm guessing it's failing when trying to open the file.

**Comment by michaelwholley** [comment]
I should note, the issue on non-Oracle distros has been fixed with commit d148d65

**Comment by dgoodwin** [comment]
Thanks for the addition @michaelwholley . Couple nitpicks, vast majority of our hits are on Red Hat systems, and technically speaking exception handling could be considered expensive so in a perfect world I'd rather see it try redhat-release and fallback to Oracle instead of the other way around. 

Ideally this would be unit tested as well in test_hwprobe.py

**Comment by dgoodwin** [comment]
Worth squashing into one commit as well given how simple it ended up being.

**Comment by michaelwholley** [comment]
Thanks for the reply @dgoodwin. I'm not sure how to squash into one commit, but I'll look into that going forward. As for falling back to Oracle, that wouldn't work since the redhat-release file exists on Oracle boxes and it would always grab that one hence why I had it check for Oracle first. 

You have a valid point in Oracle being a small (I'm probably the only one) user base. I just thought I would provide my two cents. As for unit tested, I don't know what that would consist of, sorry.

**Comment by dgoodwin** [comment]
Merging, thanks.

**Comment by alikins** [comment]
Reverted because of indention errors and unittest failures.

**Pull request merged**
