### PR TITLE
ENT-3276: refactor test_managercli.py by modules

### PR DESCRIPTION
**Pull request by ptoscano**
Refactor the big `test_managercli.py`, moving away from it:
- the tests for `cli_command` submodules for subscription-manager commands to own submodules
- the tests for functions in `printing_utils` to an own test

Card ID: ENT-3649

### CODE REVIEW

**Review by jirihnidek — COMMENTED** [review]
I would postpone review of this PR until #2497 is merged to the master, because there could be some conflicts.

**Comment by ptoscano** [comment]
> I would postpone review of this PR until #2497 is merged to the master, because there could be some conflicts.

True; OTOH the changes to `test_managercli` are small, and can be easily moved to the split file.

**Review by jirihnidek — CHANGES_REQUESTED** [review]
Thanks for the PR, but tests in new files are not triggered by nosetest, when you run simple `nosetest` in the root of source code. When you run `nosetest test/cli_command_test/`, then it doesn't do anything too.

What's wrong? New files do not begin with `test_`.

Please squash commits into the one commit.

**Comment by ptoscano** [comment]
> Please squash commits into the one commit.

Uhm, isn't splitting each class separately easier for review and later inspection of commits? IMHO big commits tend to be hard to be read/inspected later on.

**Comment by jirihnidek** [comment]
> > Please squash commits into the one commit.
> 
> Uhm, isn't splitting each class separately easier for review and later inspection of commits? IMHO big commits tend to be hard to be read/inspected later on.

We do review per PR not per commit. If it will be necessary to cherry pick this change to some release branch, then cherry picking of 26 commits is something I would like to avoid. I don't think that later inspecting of this big change would be problem.

**Review by jirihnidek — APPROVED** [review]
ACK

**Pull request merged**
