### PR TITLE
Use list of valid syspurpose values provided by candlepin server; ENT-2371

### PR DESCRIPTION
**Pull request by jirihnidek**
* Following commands of subscription-manager were extended:
  - addons
  - role
  - usage
* These commands have new CLI options --list, --username, --password
  --org, --token and --show
* When --list option is used, then list of valid values for given
  organization is printed to stdout
* When system is not registered, then --username and --password
  CLI option has to be also used. Option --org is optional in this
  case. When --org is not provided, then subscription-manager will
  ask for this value
* The --token can be also used for authentication
* When user tries to set new value, then this value is checked
  against the list of supported values. When the value is not
  listed in the list or list does not exist, then warning message
  is printed to stdout, but the provided value is set.
* When user tries to set value and --username, --password and
  --org is also provided, then new value is also checked agains
  list provided by candlepin server
* Not added --serverurl and --insecure CLI option, because such
  options will be probably marked as deprecated for many commands
* New cache was added for valid_fields (syspurpose values provided
  by candlepin) and current organization (owner). To minimize communication
  with candlepin server.
* Caching of owner is also used in e.g. org command
* Caching of supported resources was extended. It is used not only
  by roles, usage and addons command, but it is used on all places
  in sub-man
* Refactored little bit service-level command
* Updated existing unit tests
* Extended bash completion scripts to support new CLI options
* Extended man pages (sections about role, usage and addons commands
  were completely missing)
* NOTE: valid values provided by candlepin server are not used at
  all by syspurpose CLI tool.

### CODE REVIEW

**Comment by wottop** [comment]
When addons --list is called with an incorrect password, we get a 401 and a stack trace. With registration we get a 401 and only an error message.

**Comment by wottop** [comment]
When I register and then run usage--list next, I get "HTTP error (403 - Forbidden): Insufficient permissions" and a stack trace.
If I add name/password to the command [I am still registered], it works correctly.
I can then run it without the name/password.

**Comment by jirihnidek** [comment]
@wottop Interesting. I cannot observe such behavior. What candlepin server do you use for testing? Or what is content of file: `/var/lib/rhsm/cache/valid_fields.json`?

**Comment by wottop** [comment]
@jirihnidek Against my local CP running 2.10

sudo cat /var/lib/rhsm/cache/valid_fields.json
{"2247a8bd-dff5-40ea-9f34-f8d6e1974230": {"owner": {"id": "8a8d095672e263600172e263a6040003", "key": "admin", "displayName": "Admin Owner", "href": "/owners/admin"}, "systemPurposeAttributes": {"addons": ["ADDON1", "ADDON3", "ADDON2"], "usage": ["Production", "Development"], "role": ["SP Starter", "SP Server"], "se
rvice_level_agreement": ["Full-Service", "Super", "Layered", "Standard", "Premium", "None"]}}}

**Comment by jirihnidek** [comment]
@wottop Hi, I'm sorry. I cannot reproduce this issue with Python2 nor Python3. Can you please share full traceback?

I fixed one issue with version command, when system was not registered.

**Comment by wottop** [comment]
@jirihnidek - WIth the last update, I still get a 403 under the conditions above, but it is logged.
I do not get values for the lists but can confirm that they are available.

**Comment by jirihnidek** [comment]
@wottop Do you think that behavior of candlepin server is wrong. How did you deploy candlepin server? I deployed candlepin server using: `./server/bin/deploy -gtar` (master branch) and it works as expected.

**Comment by wottop** [comment]
@jirihnidek I have been using 2.10, but will try master.

**Comment by wottop** [comment]
@jirihnidek I ran it against master, and it looks like it works. Please squash and I'll ack.

**Comment by jirihnidek** [comment]
buildbot: retest this please

**Comment by jirihnidek** [comment]
@candlepin-bot retest this please

**Comment by wottop** [comment]
ack

**Pull request merged**
