### PR TITLE
1185958: Make ostree plugin depend on ostree.

### PR DESCRIPTION
**Pull request by alikins**

### CODE REVIEW

**Comment by wottop** [comment]
Requires ostree for tito build to succeed.

**Comment by alikins** [comment]
pastebin of tito errors?
```
[subscription-manager]$ rpm -qa | grep ostree
[subscription-manager]$ tito build --test --rpm
```
Works for me

**Comment by wottop** [comment]
Is the ostree plugin supposed to not get build if ostree is not installed or is it supposed to error on the tito build?

On 7.2 nightly:
rpm -qa | grep ostree
subscription-manager-plugin-ostree-1.16.0-1.git.43.4ce326b.el7.x86_64

on tito build -i --rpm --test
########## ERROR ############
Error running command: sudo rpm -Uvh --force /tmp/tito/x86_64/subscription-manager-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-plugin-ostree-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-plugin-container-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-gui-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-initial-setup-addon-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-migration-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-debuginfo-1.16.0-1.git.3.13004a0.el7.x86_64.rpm
Status code: 1792
Command output: error: Failed dependencies:
	ostree is needed by subscription-manager-plugin-ostree-1.16.0-1.git.3.13004a0.el7.x86_64
Traceback (most recent call last):
  File "/usr/bin/tito", line 5, in <module>
    pkg_resources.run_script('tito==0.5.6', 'tito')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tito-0.5.6-py2.7.egg/EGG-INFO/scripts/tito", line 23, in <module>
    
  File "build/bdist.linux-x86_64/egg/tito/cli.py", line 225, in main
  File "build/bdist.linux-x86_64/egg/tito/cli.py", line 391, in main
  File "build/bdist.linux-x86_64/egg/tito/builder/main.py", line 143, in run
  File "build/bdist.linux-x86_64/egg/tito/builder/main.py", line 294, in _auto_install
  File "build/bdist.linux-x86_64/egg/tito/common.py", line 303, in run_command
tito.exception.RunCommandException: Error running command: sudo rpm -Uvh --force /tmp/tito/x86_64/subscription-manager-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-plugin-ostree-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-plugin-container-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-gui-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-initial-setup-addon-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-migration-1.16.0-1.git.3.13004a0.el7.x86_64.rpm /tmp/tito/x86_64/subscription-manager-debuginfo-1.16.0-1.git.3.13004a0.el7.x86_64.rpm

**Comment by awood** [comment]
@wottop The plugin should always be built.  In the error you posted, it looks like it's an error in the `-i` portion of Tito.  I.e. the package built but can't install because ostree is missing.

**Comment by wottop** [comment]
@awood, good call. 

ack

**Pull request merged**
