### PR TITLE
Only build initial-setup rpm on rhel > 7.1

### PR DESCRIPTION
**Pull request by alikins**

### CODE REVIEW

**Comment by dgoodwin** [comment]
**Build Log**
*last 10 lines*

 ```
[...truncated 347 lines...]
[htmlpublisher] Archiving at BUILD level /home/jenkins/workspace/subscription-manager-nose-tests-pull-request-builder/cover to /jenkins-results/rhsm-jenkins/jobs/subscription-manager-nose-tests-pull-request-builder/builds/383/htmlreports/Coverage_module_html_report
Recording test results
Sending e-mails to: chainsaw@redhat.com
IRC notifier plugin: Sending notification to: #candlepin
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Setting status of db8daacc64cd8611ad5965bda73f075241c18b67 to FAILURE with url http://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/subscription-manager-nose-tests-pull-request-builder/383/ and message: 'Build finished.'
```

**Comment by alikins** [comment]
buildbot, retest this please

**Comment by dgoodwin** [comment]
**Build Log**
*last 10 lines*

 ```
[...truncated 347 lines...]
[htmlpublisher] Archiving at BUILD level /home/jenkins/workspace/subscription-manager-nose-tests-pull-request-builder/cover to /jenkins-results/rhsm-jenkins/jobs/subscription-manager-nose-tests-pull-request-builder/builds/386/htmlreports/Coverage_module_html_report
Recording test results
Sending e-mails to: chainsaw@redhat.com
IRC notifier plugin: Sending notification to: #candlepin
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Setting status of db8daacc64cd8611ad5965bda73f075241c18b67 to FAILURE with url http://rhsm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/subscription-manager-nose-tests-pull-request-builder/386/ and message: 'Build finished.'
```

**Comment by alikins** [comment]
buildbot, retest this please

**Comment by wottop** [comment]
ack

**Pull request merged**
